/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/public/v1/query/get_activity": {
    /** Get details about an Activity */
    post: operations["PublicApiService_GetActivity"];
  };
  "/public/v1/query/get_authenticator": {
    /** Get details about an authenticator */
    post: operations["PublicApiService_GetAuthenticator"];
  };
  "/public/v1/query/get_authenticators": {
    /** Get details about authenticators for a user */
    post: operations["PublicApiService_GetAuthenticators"];
  };
  "/public/v1/query/get_organization": {
    /** Get details about an Organization */
    post: operations["PublicApiService_GetOrganization"];
  };
  "/public/v1/query/get_policy": {
    /** Get details about a Policy */
    post: operations["PublicApiService_GetPolicy"];
  };
  "/public/v1/query/get_private_key": {
    /** Get details about a Private Key */
    post: operations["PublicApiService_GetPrivateKey"];
  };
  "/public/v1/query/get_user": {
    /** Get details about a User */
    post: operations["PublicApiService_GetUser"];
  };
  "/public/v1/query/list_activities": {
    /** List all Activities within an Organization */
    post: operations["PublicApiService_GetActivities"];
  };
  "/public/v1/query/list_policies": {
    /** List all Policies within an Organization */
    post: operations["PublicApiService_GetPolicies"];
  };
  "/public/v1/query/list_private_keys": {
    /** List all Private Keys within an Organization */
    post: operations["PublicApiService_GetPrivateKeys"];
  };
  "/public/v1/query/list_users": {
    /** List all Users within an Organization */
    post: operations["PublicApiService_GetUsers"];
  };
  "/public/v1/query/whoami": {
    /** Get basic information about your current API or WebAuthN user and their organization. Affords Sub-Organization look ups via Parent Organization for WebAuthN users. */
    post: operations["PublicApiService_GetWhoami"];
  };
  "/public/v1/submit/approve_activity": {
    /** Approve an Activity */
    post: operations["PublicApiService_ApproveActivity"];
  };
  "/public/v1/submit/create_api_keys": {
    /** Add api keys to an existing User */
    post: operations["PublicApiService_CreateApiKeys"];
  };
  "/public/v1/submit/create_api_only_users": {
    /** Create API-only Users in an existing Organization */
    post: operations["PublicApiService_CreateApiOnlyUsers"];
  };
  "/public/v1/submit/create_authenticators": {
    /** Create Authenticators to authenticate requests to Turnkey */
    post: operations["PublicApiService_CreateAuthenticators"];
  };
  "/public/v1/submit/create_invitations": {
    /** Create Invitations to join an existing Organization */
    post: operations["PublicApiService_CreateInvitations"];
  };
  "/public/v1/submit/create_policy": {
    /** Create a new Policy */
    post: operations["PublicApiService_CreatePolicy"];
  };
  "/public/v1/submit/create_private_key_tag": {
    /** Create a private key tag and add it to private keys. */
    post: operations["PublicApiService_CreatePrivateKeyTag"];
  };
  "/public/v1/submit/create_private_keys": {
    /** Create new Private Keys */
    post: operations["PublicApiService_CreatePrivateKeys"];
  };
  "/public/v1/submit/create_sub_organization": {
    /** Create a new Sub-Organization */
    post: operations["PublicApiService_CreateSubOrganization"];
  };
  "/public/v1/submit/create_user_tag": {
    /** Create a user tag and add it to users. */
    post: operations["PublicApiService_CreateUserTag"];
  };
  "/public/v1/submit/create_users": {
    /** Create Users in an existing Organization */
    post: operations["PublicApiService_CreateUsers"];
  };
  "/public/v1/submit/create_wallet": {
    /** Create a Wallet and derive addresses */
    post: operations["PublicApiService_CreateWallet"];
  };
  "/public/v1/submit/create_wallet_accounts": {
    /** Derive additional addresses using an existing wallet */
    post: operations["PublicApiService_CreateWalletAccounts"];
  };
  "/public/v1/submit/delete_api_keys": {
    /** Remove api keys from a User */
    post: operations["PublicApiService_DeleteApiKeys"];
  };
  "/public/v1/submit/delete_authenticators": {
    /** Remove authenticators from a User */
    post: operations["PublicApiService_DeleteAuthenticators"];
  };
  "/public/v1/submit/delete_invitation": {
    /** Delete an existing Invitation */
    post: operations["PublicApiService_DeleteInvitation"];
  };
  "/public/v1/submit/delete_policy": {
    /** Delete an existing Policy */
    post: operations["PublicApiService_DeletePolicy"];
  };
  "/public/v1/submit/export_private_key": {
    /** Exports a Private Key */
    post: operations["PublicApiService_ExportPrivateKey"];
  };
  "/public/v1/submit/export_wallet": {
    /** Exports a Wallet */
    post: operations["PublicApiService_ExportWallet"];
  };
  "/public/v1/submit/init_user_email_recovery": {
    /** Initializes a new email recovery */
    post: operations["PublicApiService_InitUserEmailRecovery"];
  };
  "/public/v1/submit/recover_user": {
    /** Completes the process of recovering a user by adding an authenticator */
    post: operations["PublicApiService_RecoverUser"];
  };
  "/public/v1/submit/reject_activity": {
    /** Reject an Activity */
    post: operations["PublicApiService_RejectActivity"];
  };
  "/public/v1/submit/remove_organization_feature": {
    /** Removes an organization feature */
    post: operations["PublicApiService_RemoveOrganizationFeature"];
  };
  "/public/v1/submit/set_organization_feature": {
    /** Sets an organization feature */
    post: operations["PublicApiService_SetOrganizationFeature"];
  };
  "/public/v1/submit/sign_raw_payload": {
    /** Sign a raw payload */
    post: operations["PublicApiService_SignRawPayload"];
  };
  "/public/v1/submit/sign_transaction": {
    /** Sign a transaction */
    post: operations["PublicApiService_SignTransaction"];
  };
  "/public/v1/submit/update_allowed_origins": {
    /** Update the allowable origins for credentials and requests */
    post: operations["PublicApiService_UpdateAllowedOrigins"];
  };
  "/public/v1/submit/update_policy": {
    /** Update an existing Policy */
    post: operations["PublicApiService_UpdatePolicy"];
  };
  "/public/v1/submit/update_private_key_tag": {
    /** Update human-readable name or associated private keys. Note that this activity is atomic: all of the updates will succeed at once, or all of them will fail. */
    post: operations["PublicApiService_UpdatePrivateKeyTag"];
  };
  "/public/v1/submit/update_root_quorum": {
    /** Set the threshold and members of the root quorum. This must be approved by the current root quorum. */
    post: operations["PublicApiService_UpdateRootQuorum"];
  };
  "/public/v1/submit/update_user": {
    /** Update a User in an existing Organization */
    post: operations["PublicApiService_UpdateUser"];
  };
  "/public/v1/submit/update_user_tag": {
    /** Update human-readable name or associated users. Note that this activity is atomic: all of the updates will succeed at once, or all of them will fail. */
    post: operations["PublicApiService_UpdateUserTag"];
  };
  "/tkhq/api/v1/noop-codegen-anchor": {
    post: operations["PublicApiService_NOOPCodegenAnchor"];
  };
};

export type definitions = {
  datav1Tag: {
    /** @description Unique identifier for a given Tag. */
    tagId: string;
    /** @description Human-readable name for a Tag. */
    tagName: string;
    tagType: definitions["v1TagType"];
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
  };
  /** @enum {string} */
  externaldatav1AccessType:
    | "ACCESS_TYPE_WEB"
    | "ACCESS_TYPE_API"
    | "ACCESS_TYPE_ALL";
  externaldatav1Address: {
    format?: definitions["externaldatav1AddressFormat"];
    address?: string;
  };
  /** @enum {string} */
  externaldatav1AddressFormat:
    | "ADDRESS_FORMAT_UNCOMPRESSED"
    | "ADDRESS_FORMAT_COMPRESSED"
    | "ADDRESS_FORMAT_ETHEREUM";
  /** @enum {string} */
  externaldatav1AuthenticatorTransport:
    | "AUTHENTICATOR_TRANSPORT_BLE"
    | "AUTHENTICATOR_TRANSPORT_INTERNAL"
    | "AUTHENTICATOR_TRANSPORT_NFC"
    | "AUTHENTICATOR_TRANSPORT_USB"
    | "AUTHENTICATOR_TRANSPORT_HYBRID";
  externaldatav1Credential: {
    /** @description The public component of a cryptographic key pair used to sign messages and transactions. */
    publicKey: string;
    type: definitions["externaldatav1CredentialType"];
  };
  /** @enum {string} */
  externaldatav1CredentialType:
    | "CREDENTIAL_TYPE_WEBAUTHN_AUTHENTICATOR"
    | "CREDENTIAL_TYPE_API_KEY_P256"
    | "CREDENTIAL_TYPE_RECOVER_USER_KEY_P256";
  /** @enum {string} */
  externaldatav1Curve: "CURVE_SECP256K1" | "CURVE_ED25519";
  /** @enum {string} */
  externaldatav1Effect: "EFFECT_ALLOW" | "EFFECT_DENY";
  /** @enum {string} */
  externaldatav1Operator:
    | "OPERATOR_EQUAL"
    | "OPERATOR_MORE_THAN"
    | "OPERATOR_MORE_THAN_OR_EQUAL"
    | "OPERATOR_LESS_THAN"
    | "OPERATOR_LESS_THAN_OR_EQUAL"
    | "OPERATOR_CONTAINS"
    | "OPERATOR_NOT_EQUAL"
    | "OPERATOR_IN"
    | "OPERATOR_NOT_IN"
    | "OPERATOR_CONTAINS_ONE"
    | "OPERATOR_CONTAINS_ALL";
  externaldatav1Quorum: {
    /**
     * Format: int32
     * @description Count of unique approvals required to meet quorum.
     */
    threshold: number;
    /** @description Unique identifiers of quorum set members. */
    userIds: string[];
  };
  externaldatav1Selector: {
    /** @description The resource being referenced within a policy (e.g., user.tags or activities.type). */
    subject: string;
    /** @description Logical operators like OPERATOR_CONTAINS or OPERATOR_EQUAL. */
    operator: definitions["externaldatav1Operator"];
    /** @description The specific parameter from the subject being referenced, like a specific user ID. */
    targets: string[];
  };
  externaldatav1Timestamp: {
    seconds: string;
    nanos: string;
  };
  /** @enum {string} */
  immutableactivityv1AccessType:
    | "ACCESS_TYPE_WEB"
    | "ACCESS_TYPE_API"
    | "ACCESS_TYPE_ALL";
  immutableactivityv1Address: {
    format?: definitions["immutablecommonv1AddressFormat"];
    address?: string;
  };
  /** @enum {string} */
  immutableactivityv1Effect: "EFFECT_ALLOW" | "EFFECT_DENY";
  /** @enum {string} */
  immutableactivityv1HashFunction:
    | "HASH_FUNCTION_NO_OP"
    | "HASH_FUNCTION_SHA256"
    | "HASH_FUNCTION_KECCAK256"
    | "HASH_FUNCTION_NOT_APPLICABLE";
  /** @enum {string} */
  immutableactivityv1Operator:
    | "OPERATOR_EQUAL"
    | "OPERATOR_MORE_THAN"
    | "OPERATOR_MORE_THAN_OR_EQUAL"
    | "OPERATOR_LESS_THAN"
    | "OPERATOR_LESS_THAN_OR_EQUAL"
    | "OPERATOR_CONTAINS"
    | "OPERATOR_NOT_EQUAL"
    | "OPERATOR_IN"
    | "OPERATOR_NOT_IN"
    | "OPERATOR_CONTAINS_ONE"
    | "OPERATOR_CONTAINS_ALL";
  /** @enum {string} */
  immutableactivityv1PayloadEncoding:
    | "PAYLOAD_ENCODING_HEXADECIMAL"
    | "PAYLOAD_ENCODING_TEXT_UTF8";
  immutableactivityv1Selector: {
    subject?: string;
    operator?: definitions["immutableactivityv1Operator"];
    target?: string;
  };
  /** @enum {string} */
  immutablecommonv1AddressFormat:
    | "ADDRESS_FORMAT_UNCOMPRESSED"
    | "ADDRESS_FORMAT_COMPRESSED"
    | "ADDRESS_FORMAT_ETHEREUM"
    | "ADDRESS_FORMAT_SOLANA"
    | "ADDRESS_FORMAT_COSMOS";
  /** @enum {string} */
  immutablecommonv1Curve: "CURVE_SECP256K1" | "CURVE_ED25519";
  /** @enum {string} */
  immutablewebauthnv1AuthenticatorTransport:
    | "AUTHENTICATOR_TRANSPORT_BLE"
    | "AUTHENTICATOR_TRANSPORT_INTERNAL"
    | "AUTHENTICATOR_TRANSPORT_NFC"
    | "AUTHENTICATOR_TRANSPORT_USB"
    | "AUTHENTICATOR_TRANSPORT_HYBRID";
  protobufAny: {
    "@type"?: string;
  } & { [key: string]: unknown };
  rpcStatus: {
    /** Format: int32 */
    code?: number;
    message?: string;
    details?: definitions["protobufAny"][];
  };
  v1AcceptInvitationIntent: {
    /** @description Unique identifier for a given Invitation object. */
    invitationId: string;
    /** @description Unique identifier for a given User. */
    userId: string;
    /** @description WebAuthN hardware devices that can be used to log in to the Turnkey web app. */
    authenticator: definitions["v1AuthenticatorParams"];
  };
  v1AcceptInvitationIntentV2: {
    /** @description Unique identifier for a given Invitation object. */
    invitationId: string;
    /** @description Unique identifier for a given User. */
    userId: string;
    /** @description WebAuthN hardware devices that can be used to log in to the Turnkey web app. */
    authenticator: definitions["v1AuthenticatorParamsV2"];
  };
  v1AcceptInvitationResult: {
    /** @description Unique identifier for a given Invitation. */
    invitationId: string;
    /** @description Unique identifier for a given User. */
    userId: string;
  };
  v1ActivateBillingTierIntent: {
    /** @description The product that the customer wants to subscribe to. */
    productId: string;
  };
  v1ActivateBillingTierResult: {
    /** @description The id of the product being subscribed to. */
    productId: string;
  };
  v1Activity: {
    /** @description Unique identifier for a given Activity object. */
    id: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description The current processing status of a specified Activity. */
    status: definitions["v1ActivityStatus"];
    /** @description Type of Activity, such as Add User, or Sign Transaction. */
    type: definitions["v1ActivityType"];
    /** @description Intent object crafted by Turnkey based on the user request, used to assess the permissibility of an action. */
    intent: definitions["v1Intent"];
    /** @description Result of the intended action. */
    result: definitions["v1Result"];
    /** @description A list of objects representing a particular User's approval or rejection of a Consensus request, including all relevant metadata. */
    votes: definitions["v1Vote"][];
    /** @description An artifact verifying a User's action. */
    fingerprint: string;
    canApprove: boolean;
    canReject: boolean;
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
  };
  v1ActivityResponse: {
    /** @description An action that can that can be taken within the Turnkey infrastructure. */
    activity: definitions["v1Activity"];
  };
  /** @enum {string} */
  v1ActivityStatus:
    | "ACTIVITY_STATUS_CREATED"
    | "ACTIVITY_STATUS_PENDING"
    | "ACTIVITY_STATUS_COMPLETED"
    | "ACTIVITY_STATUS_FAILED"
    | "ACTIVITY_STATUS_CONSENSUS_NEEDED"
    | "ACTIVITY_STATUS_REJECTED";
  /** @enum {string} */
  v1ActivityType:
    | "ACTIVITY_TYPE_CREATE_API_KEYS"
    | "ACTIVITY_TYPE_CREATE_USERS"
    | "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS"
    | "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD"
    | "ACTIVITY_TYPE_CREATE_INVITATIONS"
    | "ACTIVITY_TYPE_ACCEPT_INVITATION"
    | "ACTIVITY_TYPE_CREATE_POLICY"
    | "ACTIVITY_TYPE_DISABLE_PRIVATE_KEY"
    | "ACTIVITY_TYPE_DELETE_USERS"
    | "ACTIVITY_TYPE_DELETE_API_KEYS"
    | "ACTIVITY_TYPE_DELETE_INVITATION"
    | "ACTIVITY_TYPE_DELETE_ORGANIZATION"
    | "ACTIVITY_TYPE_DELETE_POLICY"
    | "ACTIVITY_TYPE_CREATE_USER_TAG"
    | "ACTIVITY_TYPE_DELETE_USER_TAGS"
    | "ACTIVITY_TYPE_CREATE_ORGANIZATION"
    | "ACTIVITY_TYPE_SIGN_TRANSACTION"
    | "ACTIVITY_TYPE_APPROVE_ACTIVITY"
    | "ACTIVITY_TYPE_REJECT_ACTIVITY"
    | "ACTIVITY_TYPE_DELETE_AUTHENTICATORS"
    | "ACTIVITY_TYPE_CREATE_AUTHENTICATORS"
    | "ACTIVITY_TYPE_CREATE_PRIVATE_KEY_TAG"
    | "ACTIVITY_TYPE_DELETE_PRIVATE_KEY_TAGS"
    | "ACTIVITY_TYPE_SET_PAYMENT_METHOD"
    | "ACTIVITY_TYPE_ACTIVATE_BILLING_TIER"
    | "ACTIVITY_TYPE_DELETE_PAYMENT_METHOD"
    | "ACTIVITY_TYPE_CREATE_POLICY_V2"
    | "ACTIVITY_TYPE_CREATE_POLICY_V3"
    | "ACTIVITY_TYPE_CREATE_API_ONLY_USERS"
    | "ACTIVITY_TYPE_UPDATE_ROOT_QUORUM"
    | "ACTIVITY_TYPE_UPDATE_USER_TAG"
    | "ACTIVITY_TYPE_UPDATE_PRIVATE_KEY_TAG"
    | "ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2"
    | "ACTIVITY_TYPE_CREATE_ORGANIZATION_V2"
    | "ACTIVITY_TYPE_CREATE_USERS_V2"
    | "ACTIVITY_TYPE_ACCEPT_INVITATION_V2"
    | "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION"
    | "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V2"
    | "ACTIVITY_TYPE_UPDATE_ALLOWED_ORIGINS"
    | "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2"
    | "ACTIVITY_TYPE_UPDATE_USER"
    | "ACTIVITY_TYPE_UPDATE_POLICY"
    | "ACTIVITY_TYPE_SET_PAYMENT_METHOD_V2"
    | "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V3"
    | "ACTIVITY_TYPE_CREATE_WALLET"
    | "ACTIVITY_TYPE_CREATE_WALLET_ACCOUNTS"
    | "ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY"
    | "ACTIVITY_TYPE_RECOVER_USER"
    | "ACTIVITY_TYPE_SET_ORGANIZATION_FEATURE"
    | "ACTIVITY_TYPE_REMOVE_ORGANIZATION_FEATURE"
    | "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2"
    | "ACTIVITY_TYPE_SIGN_TRANSACTION_V2"
    | "ACTIVITY_TYPE_EXPORT_PRIVATE_KEY"
    | "ACTIVITY_TYPE_EXPORT_WALLET"
    | "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V4";
  v1ApiKey: {
    /** @description A User credential that can be used to authenticate to Turnkey. */
    credential: definitions["externaldatav1Credential"];
    /** @description Unique identifier for a given API Key. */
    apiKeyId: string;
    /** @description Human-readable name for an API Key. */
    apiKeyName: string;
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
  };
  v1ApiKeyParams: {
    /** @description Human-readable name for an API Key. */
    apiKeyName: string;
    /** @description The public component of a cryptographic key pair used to sign messages and transactions. */
    publicKey: string;
  };
  v1ApiOnlyUserParams: {
    /** @description The name of the new API-only User. */
    userName: string;
    /** @description The email address for this API-only User (optional). */
    userEmail?: string;
    /** @description A list of tags assigned to the new API-only User. */
    userTags: string[];
    /** @description A list of API Key parameters. */
    apiKeys: definitions["v1ApiKeyParams"][];
  };
  v1ApproveActivityIntent: {
    /** @description An artifact verifying a User's action. */
    fingerprint: string;
  };
  v1ApproveActivityRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_APPROVE_ACTIVITY";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1ApproveActivityIntent"];
  };
  v1Attestation: {
    /** @description The cbor encoded then base64 url encoded id of the credential. */
    credentialId: string;
    /** @description A base64 url encoded payload containing metadata about the signing context and the challenge. */
    clientDataJson: string;
    /** @description A base64 url encoded payload containing authenticator data and any attestation the webauthn provider chooses. */
    attestationObject: string;
    /** @description The type of authenticator transports. */
    transports: definitions["immutablewebauthnv1AuthenticatorTransport"][];
  };
  v1Authenticator: {
    /** @description Types of transports that may be used by an Authenticator (e.g., USB, NFC, BLE). */
    transports: definitions["externaldatav1AuthenticatorTransport"][];
    attestationType: string;
    /** @description Identifier indicating the type of the Security Key. */
    aaguid: string;
    /** @description Unique identifier for a WebAuthn credential. */
    credentialId: string;
    /** @description The type of Authenticator device. */
    model: string;
    /** @description A User credential that can be used to authenticate to Turnkey. */
    credential: definitions["externaldatav1Credential"];
    /** @description Unique identifier for a given Authenticator. */
    authenticatorId: string;
    /** @description Human-readable name for an Authenticator. */
    authenticatorName: string;
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
  };
  v1AuthenticatorAttestationResponse: {
    clientDataJson: string;
    attestationObject: string;
    transports?: definitions["immutablewebauthnv1AuthenticatorTransport"][];
    /** @enum {string} */
    authenticatorAttachment?: "cross-platform" | "platform" | null;
  };
  v1AuthenticatorParams: {
    /** @description Human-readable name for an Authenticator. */
    authenticatorName: string;
    /** @description Unique identifier for a given User. */
    userId: string;
    attestation: definitions["v1PublicKeyCredentialWithAttestation"];
    /** @description Challenge presented for authentication purposes. */
    challenge: string;
  };
  v1AuthenticatorParamsV2: {
    /** @description Human-readable name for an Authenticator. */
    authenticatorName: string;
    /** @description Challenge presented for authentication purposes. */
    challenge: string;
    /** @description The attestation that proves custody of the authenticator and provides metadata about it. */
    attestation: definitions["v1Attestation"];
  };
  v1CreateApiKeysIntent: {
    /** @description A list of API Keys. */
    apiKeys: definitions["v1ApiKeyParams"][];
    /** @description Unique identifier for a given User. */
    userId: string;
  };
  v1CreateApiKeysRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_API_KEYS";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateApiKeysIntent"];
  };
  v1CreateApiKeysResult: {
    /** @description A list of API Key IDs. */
    apiKeyIds: string[];
  };
  v1CreateApiOnlyUsersIntent: {
    /** @description A list of API-only Users to create. */
    apiOnlyUsers: definitions["v1ApiOnlyUserParams"][];
  };
  v1CreateApiOnlyUsersRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_API_ONLY_USERS";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateApiOnlyUsersIntent"];
  };
  v1CreateApiOnlyUsersResult: {
    /** @description A list of API-only User IDs. */
    userIds: string[];
  };
  v1CreateAuthenticatorsIntent: {
    /** @description A list of Authenticators. */
    authenticators: definitions["v1AuthenticatorParams"][];
    /** @description Unique identifier for a given User. */
    userId: string;
  };
  v1CreateAuthenticatorsIntentV2: {
    /** @description A list of Authenticators. */
    authenticators: definitions["v1AuthenticatorParamsV2"][];
    /** @description Unique identifier for a given User. */
    userId: string;
  };
  v1CreateAuthenticatorsRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateAuthenticatorsIntentV2"];
  };
  v1CreateAuthenticatorsResult: {
    /** @description A list of Authenticator IDs. */
    authenticatorIds: string[];
  };
  v1CreateInvitationsIntent: {
    /** @description A list of Invitations. */
    invitations: definitions["v1InvitationParams"][];
  };
  v1CreateInvitationsRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_INVITATIONS";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateInvitationsIntent"];
  };
  v1CreateInvitationsResult: {
    /** @description A list of Invitation IDs */
    invitationIds: string[];
  };
  v1CreateOrganizationIntent: {
    /** @description Human-readable name for an Organization. */
    organizationName: string;
    /** @description The root user's email address. */
    rootEmail: string;
    /** @description The root user's Authenticator. */
    rootAuthenticator: definitions["v1AuthenticatorParams"];
    /** @description Unique identifier for the root user object. */
    rootUserId?: string;
  };
  v1CreateOrganizationIntentV2: {
    /** @description Human-readable name for an Organization. */
    organizationName: string;
    /** @description The root user's email address. */
    rootEmail: string;
    /** @description The root user's Authenticator. */
    rootAuthenticator: definitions["v1AuthenticatorParamsV2"];
    /** @description Unique identifier for the root user object. */
    rootUserId?: string;
  };
  v1CreateOrganizationResult: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
  };
  v1CreatePolicyIntent: {
    /** @description Human-readable name for a Policy. */
    policyName: string;
    /** @description A list of simple functions each including a subject, target and boolean. See Policy Engine Language section for additional details. */
    selectors: definitions["immutableactivityv1Selector"][];
    /** @description The instruction to DENY or ALLOW a particular activity following policy selector(s). */
    effect: definitions["immutableactivityv1Effect"];
    notes?: string;
  };
  v1CreatePolicyIntentV2: {
    /** @description Human-readable name for a Policy. */
    policyName: string;
    /** @description A list of simple functions each including a subject, target and boolean. See Policy Engine Language section for additional details. */
    selectors: definitions["v1SelectorV2"][];
    /** @description Whether to ALLOW or DENY requests that match the condition and consensus requirements. */
    effect: definitions["immutableactivityv1Effect"];
    notes?: string;
  };
  v1CreatePolicyIntentV3: {
    /** @description Human-readable name for a Policy. */
    policyName: string;
    /** @description The instruction to DENY or ALLOW an activity. */
    effect: definitions["immutableactivityv1Effect"];
    /** @description The condition expression that triggers the Effect */
    condition?: string;
    /** @description The consensus expression that triggers the Effect */
    consensus?: string;
    notes?: string;
  };
  v1CreatePolicyRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_POLICY_V3";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreatePolicyIntentV3"];
  };
  v1CreatePolicyResult: {
    /** @description Unique identifier for a given Policy. */
    policyId: string;
  };
  v1CreatePrivateKeyTagIntent: {
    /** @description Human-readable name for a Private Key Tag. */
    privateKeyTagName: string;
    /** @description A list of Private Key IDs. */
    privateKeyIds: string[];
  };
  v1CreatePrivateKeyTagRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_PRIVATE_KEY_TAG";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreatePrivateKeyTagIntent"];
  };
  v1CreatePrivateKeyTagResult: {
    /** @description Unique identifier for a given Private Key Tag. */
    privateKeyTagId: string;
    /** @description A list of Private Key IDs. */
    privateKeyIds: string[];
  };
  v1CreatePrivateKeysIntent: {
    /** @description A list of Private Keys. */
    privateKeys: definitions["v1PrivateKeyParams"][];
  };
  v1CreatePrivateKeysIntentV2: {
    /** @description A list of Private Keys. */
    privateKeys: definitions["v1PrivateKeyParams"][];
  };
  v1CreatePrivateKeysRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreatePrivateKeysIntentV2"];
  };
  v1CreatePrivateKeysResult: {
    /** @description A list of Private Key IDs. */
    privateKeyIds: string[];
  };
  v1CreatePrivateKeysResultV2: {
    /** @description A list of Private Key IDs and addresses. */
    privateKeys: definitions["v1PrivateKeyResult"][];
  };
  v1CreateSubOrganizationIntent: {
    /** @description Name for this sub-organization */
    name: string;
    /** @description Root User authenticator for this new sub-organization */
    rootAuthenticator: definitions["v1AuthenticatorParamsV2"];
  };
  v1CreateSubOrganizationIntentV2: {
    /** @description Name for this sub-organization */
    subOrganizationName: string;
    /** @description Root users to create within this sub-organization */
    rootUsers: definitions["v1RootUserParams"][];
    /**
     * Format: int32
     * @description The threshold of unique approvals to reach root quorum. This value must be less than or equal to the number of root users
     */
    rootQuorumThreshold: number;
  };
  v1CreateSubOrganizationIntentV3: {
    /** @description Name for this sub-organization */
    subOrganizationName: string;
    /** @description Root users to create within this sub-organization */
    rootUsers: definitions["v1RootUserParams"][];
    /**
     * Format: int32
     * @description The threshold of unique approvals to reach root quorum. This value must be less than or equal to the number of root users
     */
    rootQuorumThreshold: number;
    /** @description A list of Private Keys. */
    privateKeys: definitions["v1PrivateKeyParams"][];
  };
  v1CreateSubOrganizationIntentV4: {
    /** @description Name for this sub-organization */
    subOrganizationName: string;
    /** @description Root users to create within this sub-organization */
    rootUsers: definitions["v1RootUserParams"][];
    /**
     * Format: int32
     * @description The threshold of unique approvals to reach root quorum. This value must be less than or equal to the number of root users
     */
    rootQuorumThreshold: number;
    /** @description The wallet to create for the sub-organization */
    wallet?: definitions["v1WalletParams"];
    /** @description Disable email recovery for the sub-organization */
    disableEmailRecovery?: boolean;
  };
  v1CreateSubOrganizationRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V4";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateSubOrganizationIntentV4"];
  };
  v1CreateSubOrganizationResult: {
    subOrganizationId: string;
  };
  v1CreateSubOrganizationResultV3: {
    subOrganizationId: string;
    /** @description A list of Private Key IDs and addresses. */
    privateKeys: definitions["v1PrivateKeyResult"][];
  };
  v1CreateSubOrganizationResultV4: {
    subOrganizationId: string;
    wallet?: definitions["v1WalletResult"];
  };
  v1CreateUserTagIntent: {
    /** @description Human-readable name for a User Tag. */
    userTagName: string;
    /** @description A list of User IDs. */
    userIds: string[];
  };
  v1CreateUserTagRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_USER_TAG";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateUserTagIntent"];
  };
  v1CreateUserTagResult: {
    /** @description Unique identifier for a given User Tag. */
    userTagId: string;
    /** @description A list of User IDs. */
    userIds: string[];
  };
  v1CreateUsersIntent: {
    /** @description A list of Users. */
    users: definitions["v1UserParams"][];
  };
  v1CreateUsersIntentV2: {
    /** @description A list of Users. */
    users: definitions["v1UserParamsV2"][];
  };
  v1CreateUsersRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_USERS_V2";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateUsersIntentV2"];
  };
  v1CreateUsersResult: {
    /** @description A list of User IDs. */
    userIds: string[];
  };
  v1CreateWalletAccountsIntent: {
    /** @description Unique identifier for a given Wallet. */
    walletId: string;
    /** @description A list of wallet Accounts. */
    accounts: definitions["v1WalletAccountParams"][];
  };
  v1CreateWalletAccountsRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_WALLET_ACCOUNTS";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateWalletAccountsIntent"];
  };
  v1CreateWalletAccountsResult: {
    /** @description A list of derived addresses. */
    addresses: string[];
  };
  v1CreateWalletIntent: {
    /** @description Human-readable name for a Wallet. */
    walletName: string;
    /** @description A list of wallet Accounts. */
    accounts: definitions["v1WalletAccountParams"][];
  };
  v1CreateWalletRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_CREATE_WALLET";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1CreateWalletIntent"];
  };
  v1CreateWalletResult: {
    /** @description A list of Wallet IDs. */
    walletId: string;
    /** @description A list of account addresses. */
    addresses: string[];
  };
  v1CredPropsAuthenticationExtensionsClientOutputs: {
    rk: boolean;
  };
  v1DeleteApiKeysIntent: {
    /** @description Unique identifier for a given User. */
    userId: string;
    /** @description A list of API Key IDs. */
    apiKeyIds: string[];
  };
  v1DeleteApiKeysRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_DELETE_API_KEYS";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1DeleteApiKeysIntent"];
  };
  v1DeleteApiKeysResult: {
    /** @description A list of API Key IDs. */
    apiKeyIds: string[];
  };
  v1DeleteAuthenticatorsIntent: {
    /** @description Unique identifier for a given User. */
    userId: string;
    /** @description A list of Authenticator IDs. */
    authenticatorIds: string[];
  };
  v1DeleteAuthenticatorsRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_DELETE_AUTHENTICATORS";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1DeleteAuthenticatorsIntent"];
  };
  v1DeleteAuthenticatorsResult: {
    /** @description Unique identifier for a given Authenticator. */
    authenticatorIds: string[];
  };
  v1DeleteInvitationIntent: {
    /** @description Unique identifier for a given Invitation object. */
    invitationId: string;
  };
  v1DeleteInvitationRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_DELETE_INVITATION";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1DeleteInvitationIntent"];
  };
  v1DeleteInvitationResult: {
    /** @description Unique identifier for a given Invitation. */
    invitationId: string;
  };
  v1DeleteOrganizationIntent: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
  };
  v1DeleteOrganizationResult: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
  };
  v1DeletePaymentMethodIntent: {
    /** @description The payment method that the customer wants to remove. */
    paymentMethodId: string;
  };
  v1DeletePaymentMethodResult: {
    /** @description The payment method that was removed. */
    paymentMethodId: string;
  };
  v1DeletePolicyIntent: {
    /** @description Unique identifier for a given Policy. */
    policyId: string;
  };
  v1DeletePolicyRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_DELETE_POLICY";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1DeletePolicyIntent"];
  };
  v1DeletePolicyResult: {
    /** @description Unique identifier for a given Policy. */
    policyId: string;
  };
  v1DeletePrivateKeyTagsIntent: {
    /** @description A list of Private Key Tag IDs. */
    privateKeyTagIds: string[];
  };
  v1DeletePrivateKeyTagsResult: {
    /** @description A list of Private Key Tag IDs. */
    privateKeyTagIds: string[];
    /** @description A list of Private Key IDs. */
    privateKeyIds: string[];
  };
  v1DeleteUserTagsIntent: {
    /** @description A list of User Tag IDs. */
    userTagIds: string[];
  };
  v1DeleteUserTagsResult: {
    /** @description A list of User Tag IDs. */
    userTagIds: string[];
    /** @description A list of User IDs. */
    userIds: string[];
  };
  v1DeleteUsersIntent: {
    /** @description A list of User IDs. */
    userIds: string[];
  };
  v1DeleteUsersResult: {
    /** @description A list of User IDs. */
    userIds: string[];
  };
  v1DisablePrivateKeyIntent: {
    /** @description Unique identifier for a given Private Key. */
    privateKeyId: string;
  };
  v1DisablePrivateKeyResult: {
    /** @description Unique identifier for a given Private Key. */
    privateKeyId: string;
  };
  v1ExportPrivateKeyIntent: {
    /** @description Unique identifier for a given Private Key. */
    privateKeyId: string;
    /** @description Client-side public key generated by the user, to which the export bundle will be encrypted. */
    targetPublicKey: string;
  };
  v1ExportPrivateKeyRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_EXPORT_PRIVATE_KEY";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1ExportPrivateKeyIntent"];
  };
  v1ExportPrivateKeyResult: {
    /** @description Unique identifier for a given Private Key. */
    privateKeyId: string;
    /** @description Export bundle containing a private key encrypted to the client's target public key. */
    exportBundle: string;
  };
  v1ExportWalletIntent: {
    /** @description Unique identifier for a given Wallet. */
    walletId: string;
    /** @description Client-side public key generated by the user, to which the export bundle will be encrypted. */
    targetPublicKey: string;
    /** @description The language of the mnemonic to export. Defaults to English. */
    language?: definitions["v1MnemonicLanguage"];
  };
  v1ExportWalletRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_EXPORT_WALLET";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1ExportWalletIntent"];
  };
  v1ExportWalletResult: {
    /** @description Unique identifier for a given Wallet. */
    walletId: string;
    /** @description Export bundle containing a wallet mnemonic + optional newline passphrase encrypted by the client's target public key. */
    exportBundle: string;
  };
  v1Feature: {
    name?: definitions["v1FeatureName"];
    value?: string;
  };
  /** @enum {string} */
  v1FeatureName: "FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY";
  v1GetActivitiesRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description Array of Activity Statuses filtering which Activities will be listed in the response. */
    filterByStatus?: definitions["v1ActivityStatus"][];
    /** @description Parameters used for cursor-based pagination. */
    paginationOptions?: definitions["v1Pagination"];
    /** @description Array of Activity Types filtering which Activities will be listed in the response. */
    filterByType?: definitions["v1ActivityType"][];
  };
  v1GetActivitiesResponse: {
    /** @description A list of Activities. */
    activities: definitions["v1Activity"][];
  };
  v1GetActivityRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description Unique identifier for a given Activity object. */
    activityId: string;
  };
  v1GetAuthenticatorRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description Unique identifier for a given Authenticator. */
    authenticatorId: string;
  };
  v1GetAuthenticatorResponse: {
    /** @description An authenticator. */
    authenticator: definitions["v1Authenticator"];
  };
  v1GetAuthenticatorsRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description Unique identifier for a given User. */
    userId: string;
  };
  v1GetAuthenticatorsResponse: {
    /** @description A list of authenticators. */
    authenticators: definitions["v1Authenticator"][];
  };
  v1GetOrganizationRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
  };
  v1GetOrganizationResponse: {
    /** @description Object representing the full current and deleted / disabled collection of Users, Policies, Private Keys, and Invitations attributable to a particular Organization. */
    organizationData: definitions["v1OrganizationData"];
  };
  v1GetPoliciesRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
  };
  v1GetPoliciesResponse: {
    /** @description A list of Policies. */
    policies: definitions["v1Policy"][];
  };
  v1GetPolicyRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description Unique identifier for a given Policy. */
    policyId: string;
  };
  v1GetPolicyResponse: {
    /** @description Object that codifies rules defining the actions that are permissible within an Organization. */
    policy: definitions["v1Policy"];
  };
  v1GetPrivateKeyRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description Unique identifier for a given Private Key. */
    privateKeyId: string;
  };
  v1GetPrivateKeyResponse: {
    /** @description Cryptographic public/private key pair that can be used for cryptocurrency needs or more generalized encryption. */
    privateKey: definitions["v1PrivateKey"];
  };
  v1GetPrivateKeysRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
  };
  v1GetPrivateKeysResponse: {
    /** @description A list of Private Keys. */
    privateKeys: definitions["v1PrivateKey"][];
  };
  v1GetUserRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description Unique identifier for a given User. */
    userId: string;
  };
  v1GetUserResponse: {
    /** @description Web and/or API user within your Organization. */
    user: definitions["v1User"];
  };
  v1GetUsersRequest: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
  };
  v1GetUsersResponse: {
    /** @description A list of Users. */
    users: definitions["v1User"][];
  };
  v1GetWhoamiRequest: {
    /** @description Unique identifier for a given Organization. If the request is being made by a WebAuthN user and their Sub-Organization ID is unknown, this can be the Parent Organization ID; using the Sub-Organization ID when possible is preferred due to performance reasons. */
    organizationId: string;
  };
  v1GetWhoamiResponse: {
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    /** @description Human-readable name for an Organization. */
    organizationName: string;
    /** @description Unique identifier for a given User. */
    userId: string;
    /** @description Human-readable name for a User. */
    username: string;
  };
  v1InitUserEmailRecoveryIntent: {
    /** @description Email of the user starting recovery */
    email: string;
    /** @description Client-side public key generated by the user, to which the recovery bundle will be encrypted. */
    targetPublicKey: string;
  };
  v1InitUserEmailRecoveryRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1InitUserEmailRecoveryIntent"];
  };
  v1InitUserEmailRecoveryResult: {
    /** @description Unique identifier for the user being recovered. */
    userId: string;
  };
  v1Intent: {
    createOrganizationIntent: definitions["v1CreateOrganizationIntent"];
    createAuthenticatorsIntent?: definitions["v1CreateAuthenticatorsIntent"];
    createUsersIntent?: definitions["v1CreateUsersIntent"];
    createPrivateKeysIntent?: definitions["v1CreatePrivateKeysIntent"];
    signRawPayloadIntent?: definitions["v1SignRawPayloadIntent"];
    createInvitationsIntent?: definitions["v1CreateInvitationsIntent"];
    acceptInvitationIntent?: definitions["v1AcceptInvitationIntent"];
    createPolicyIntent?: definitions["v1CreatePolicyIntent"];
    disablePrivateKeyIntent?: definitions["v1DisablePrivateKeyIntent"];
    deleteUsersIntent?: definitions["v1DeleteUsersIntent"];
    deleteAuthenticatorsIntent?: definitions["v1DeleteAuthenticatorsIntent"];
    deleteInvitationIntent?: definitions["v1DeleteInvitationIntent"];
    deleteOrganizationIntent?: definitions["v1DeleteOrganizationIntent"];
    deletePolicyIntent?: definitions["v1DeletePolicyIntent"];
    createUserTagIntent?: definitions["v1CreateUserTagIntent"];
    deleteUserTagsIntent?: definitions["v1DeleteUserTagsIntent"];
    signTransactionIntent?: definitions["v1SignTransactionIntent"];
    createApiKeysIntent?: definitions["v1CreateApiKeysIntent"];
    deleteApiKeysIntent?: definitions["v1DeleteApiKeysIntent"];
    approveActivityIntent?: definitions["v1ApproveActivityIntent"];
    rejectActivityIntent?: definitions["v1RejectActivityIntent"];
    createPrivateKeyTagIntent?: definitions["v1CreatePrivateKeyTagIntent"];
    deletePrivateKeyTagsIntent?: definitions["v1DeletePrivateKeyTagsIntent"];
    createPolicyIntentV2?: definitions["v1CreatePolicyIntentV2"];
    setPaymentMethodIntent?: definitions["v1SetPaymentMethodIntent"];
    activateBillingTierIntent?: definitions["v1ActivateBillingTierIntent"];
    deletePaymentMethodIntent?: definitions["v1DeletePaymentMethodIntent"];
    createPolicyIntentV3?: definitions["v1CreatePolicyIntentV3"];
    createApiOnlyUsersIntent?: definitions["v1CreateApiOnlyUsersIntent"];
    updateRootQuorumIntent?: definitions["v1UpdateRootQuorumIntent"];
    updateUserTagIntent?: definitions["v1UpdateUserTagIntent"];
    updatePrivateKeyTagIntent?: definitions["v1UpdatePrivateKeyTagIntent"];
    createAuthenticatorsIntentV2?: definitions["v1CreateAuthenticatorsIntentV2"];
    acceptInvitationIntentV2?: definitions["v1AcceptInvitationIntentV2"];
    createOrganizationIntentV2?: definitions["v1CreateOrganizationIntentV2"];
    createUsersIntentV2?: definitions["v1CreateUsersIntentV2"];
    createSubOrganizationIntent?: definitions["v1CreateSubOrganizationIntent"];
    createSubOrganizationIntentV2?: definitions["v1CreateSubOrganizationIntentV2"];
    updateAllowedOriginsIntent?: definitions["v1UpdateAllowedOriginsIntent"];
    createPrivateKeysIntentV2?: definitions["v1CreatePrivateKeysIntentV2"];
    updateUserIntent?: definitions["v1UpdateUserIntent"];
    updatePolicyIntent?: definitions["v1UpdatePolicyIntent"];
    setPaymentMethodIntentV2?: definitions["v1SetPaymentMethodIntentV2"];
    createSubOrganizationIntentV3?: definitions["v1CreateSubOrganizationIntentV3"];
    createWalletIntent?: definitions["v1CreateWalletIntent"];
    createWalletAccountsIntent?: definitions["v1CreateWalletAccountsIntent"];
    initUserEmailRecoveryIntent?: definitions["v1InitUserEmailRecoveryIntent"];
    recoverUserIntent?: definitions["v1RecoverUserIntent"];
    setOrganizationFeatureIntent?: definitions["v1SetOrganizationFeatureIntent"];
    removeOrganizationFeatureIntent?: definitions["v1RemoveOrganizationFeatureIntent"];
    signRawPayloadIntentV2?: definitions["v1SignRawPayloadIntentV2"];
    signTransactionIntentV2?: definitions["v1SignTransactionIntentV2"];
    exportPrivateKeyIntent?: definitions["v1ExportPrivateKeyIntent"];
    exportWalletIntent?: definitions["v1ExportWalletIntent"];
    createSubOrganizationIntentV4?: definitions["v1CreateSubOrganizationIntentV4"];
  };
  v1Invitation: {
    /** @description Unique identifier for a given Invitation object. */
    invitationId: string;
    /** @description The name of the intended Invitation recipient. */
    receiverUserName: string;
    /** @description The email address of the intended Invitation recipient. */
    receiverEmail: string;
    /** @description A list of tags assigned to the Invitation recipient. */
    receiverUserTags: string[];
    /** @description The User's permissible access method(s). */
    accessType: definitions["externaldatav1AccessType"];
    /** @description The current processing status of a specified Invitation. */
    status: definitions["v1InvitationStatus"];
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
    /** @description Unique identifier for the Sender of an Invitation. */
    senderUserId: string;
  };
  v1InvitationParams: {
    /** @description The name of the intended Invitation recipient. */
    receiverUserName: string;
    /** @description The email address of the intended Invitation recipient. */
    receiverUserEmail: string;
    /** @description A list of tags assigned to the Invitation recipient. */
    receiverUserTags: string[];
    /** @description The User's permissible access method(s). */
    accessType: definitions["immutableactivityv1AccessType"];
    /** @description Unique identifier for the Sender of an Invitation. */
    senderUserId: string;
  };
  /** @enum {string} */
  v1InvitationStatus:
    | "INVITATION_STATUS_CREATED"
    | "INVITATION_STATUS_ACCEPTED"
    | "INVITATION_STATUS_REVOKED";
  /** @enum {string} */
  v1MnemonicLanguage:
    | "MNEMONIC_LANGUAGE_ENGLISH"
    | "MNEMONIC_LANGUAGE_SIMPLIFIED_CHINESE"
    | "MNEMONIC_LANGUAGE_TRADITIONAL_CHINESE"
    | "MNEMONIC_LANGUAGE_CZECH"
    | "MNEMONIC_LANGUAGE_FRENCH"
    | "MNEMONIC_LANGUAGE_ITALIAN"
    | "MNEMONIC_LANGUAGE_JAPANESE"
    | "MNEMONIC_LANGUAGE_KOREAN"
    | "MNEMONIC_LANGUAGE_SPANISH";
  v1NOOPCodegenAnchorResponse: {
    stamp: definitions["v1WebAuthnStamp"];
  };
  v1OrganizationData: {
    organizationId?: string;
    name?: string;
    users?: definitions["v1User"][];
    policies?: definitions["v1Policy"][];
    privateKeys?: definitions["v1PrivateKey"][];
    invitations?: definitions["v1Invitation"][];
    tags?: definitions["datav1Tag"][];
    disabledPrivateKeys?: definitions["v1PrivateKey"][];
    rootQuorum?: definitions["externaldatav1Quorum"];
    allowedOrigins?: string[];
    features?: definitions["v1Feature"][];
    wallets?: definitions["v1Wallet"][];
  };
  v1Pagination: {
    /** @description A limit of the number of object to be returned, between 1 and 100. Defaults to 10. */
    limit?: string;
    /** @description A pagination cursor. This is an object ID that enables you to fetch all objects before this ID. */
    before?: string;
    /** @description A pagination cursor. This is an object ID that enables you to fetch all objects after this ID. */
    after?: string;
  };
  /** @enum {string} */
  v1PathFormat: "PATH_FORMAT_BIP32";
  v1Policy: {
    /** @description Unique identifier for a given Policy. */
    policyId: string;
    /** @description Human-readable name for a Policy. */
    policyName: string;
    /** @description The instruction to DENY or ALLOW a particular activity following policy selector(s). */
    effect: definitions["externaldatav1Effect"];
    /** @description A list of simple functions each including a subject, target and boolean. See Policy Engine Language section for additional details. */
    selectors: definitions["externaldatav1Selector"][];
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
    /** @description Human-readable notes added by a User to describe a particular policy. */
    notes: string;
    /** @description A consensus expression that evalutes to true or false. */
    consensus: string;
    /** @description A condition expression that evalutes to true or false. */
    condition: string;
  };
  v1PrivateKey: {
    /** @description Unique identifier for a given Private Key. */
    privateKeyId: string;
    /** @description The public component of a cryptographic key pair used to sign messages and transactions. */
    publicKey: string;
    /** @description Human-readable name for a Private Key. */
    privateKeyName: string;
    /** @description Cryptographic Curve used to generate a given Private Key. */
    curve: definitions["externaldatav1Curve"];
    /** @description Derived cryptocurrency addresses for a given Private Key. */
    addresses: definitions["externaldatav1Address"][];
    /** @description A list of Private Key Tag IDs. */
    privateKeyTags: string[];
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
    /** @description True when a given Private Key is exported, false otherwise. */
    exported: boolean;
  };
  v1PrivateKeyParams: {
    /** @description Human-readable name for a Private Key. */
    privateKeyName: string;
    /** @description Cryptographic Curve used to generate a given Private Key. */
    curve: definitions["immutablecommonv1Curve"];
    /** @description A list of Private Key Tag IDs. */
    privateKeyTags: string[];
    /** @description Cryptocurrency-specific formats for a derived address (e.g., Ethereum). */
    addressFormats: definitions["immutablecommonv1AddressFormat"][];
  };
  v1PrivateKeyResult: {
    privateKeyId?: string;
    addresses?: definitions["immutableactivityv1Address"][];
  };
  v1PublicKeyCredentialWithAttestation: {
    id: string;
    /** @enum {string} */
    type: "public-key";
    rawId: string;
    /** @enum {string} */
    authenticatorAttachment?: "cross-platform" | "platform" | null;
    response: definitions["v1AuthenticatorAttestationResponse"];
    clientExtensionResults: definitions["v1SimpleClientExtensionResults"];
  };
  v1RecoverUserIntent: {
    /** @description The new authenticator to register. */
    authenticator: definitions["v1AuthenticatorParamsV2"];
    /** @description Unique identifier for the user performing recovery. */
    userId: string;
  };
  v1RecoverUserRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_RECOVER_USER";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1RecoverUserIntent"];
  };
  v1RecoverUserResult: {
    /** @description ID of the authenticator created. */
    authenticatorId: string[];
  };
  v1RejectActivityIntent: {
    /** @description An artifact verifying a User's action. */
    fingerprint: string;
  };
  v1RejectActivityRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_REJECT_ACTIVITY";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1RejectActivityIntent"];
  };
  v1RemoveOrganizationFeatureIntent: {
    /** @description Name of the feature to remove */
    name: definitions["v1FeatureName"];
  };
  v1RemoveOrganizationFeatureRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_REMOVE_ORGANIZATION_FEATURE";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1RemoveOrganizationFeatureIntent"];
  };
  v1RemoveOrganizationFeatureResult: {
    /** @description Resulting list of organization features. */
    features: definitions["v1Feature"][];
  };
  v1Result: {
    createOrganizationResult?: definitions["v1CreateOrganizationResult"];
    createAuthenticatorsResult?: definitions["v1CreateAuthenticatorsResult"];
    createUsersResult?: definitions["v1CreateUsersResult"];
    createPrivateKeysResult?: definitions["v1CreatePrivateKeysResult"];
    createInvitationsResult?: definitions["v1CreateInvitationsResult"];
    acceptInvitationResult?: definitions["v1AcceptInvitationResult"];
    signRawPayloadResult?: definitions["v1SignRawPayloadResult"];
    createPolicyResult?: definitions["v1CreatePolicyResult"];
    disablePrivateKeyResult?: definitions["v1DisablePrivateKeyResult"];
    deleteUsersResult?: definitions["v1DeleteUsersResult"];
    deleteAuthenticatorsResult?: definitions["v1DeleteAuthenticatorsResult"];
    deleteInvitationResult?: definitions["v1DeleteInvitationResult"];
    deleteOrganizationResult?: definitions["v1DeleteOrganizationResult"];
    deletePolicyResult?: definitions["v1DeletePolicyResult"];
    createUserTagResult?: definitions["v1CreateUserTagResult"];
    deleteUserTagsResult?: definitions["v1DeleteUserTagsResult"];
    signTransactionResult?: definitions["v1SignTransactionResult"];
    deleteApiKeysResult?: definitions["v1DeleteApiKeysResult"];
    createApiKeysResult?: definitions["v1CreateApiKeysResult"];
    createPrivateKeyTagResult?: definitions["v1CreatePrivateKeyTagResult"];
    deletePrivateKeyTagsResult?: definitions["v1DeletePrivateKeyTagsResult"];
    setPaymentMethodResult?: definitions["v1SetPaymentMethodResult"];
    activateBillingTierResult?: definitions["v1ActivateBillingTierResult"];
    deletePaymentMethodResult?: definitions["v1DeletePaymentMethodResult"];
    createApiOnlyUsersResult?: definitions["v1CreateApiOnlyUsersResult"];
    updateRootQuorumResult?: definitions["v1UpdateRootQuorumResult"];
    updateUserTagResult?: definitions["v1UpdateUserTagResult"];
    updatePrivateKeyTagResult?: definitions["v1UpdatePrivateKeyTagResult"];
    createSubOrganizationResult?: definitions["v1CreateSubOrganizationResult"];
    updateAllowedOriginsResult?: definitions["v1UpdateAllowedOriginsResult"];
    createPrivateKeysResultV2?: definitions["v1CreatePrivateKeysResultV2"];
    updateUserResult?: definitions["v1UpdateUserResult"];
    updatePolicyResult?: definitions["v1UpdatePolicyResult"];
    createSubOrganizationResultV3?: definitions["v1CreateSubOrganizationResultV3"];
    createWalletResult?: definitions["v1CreateWalletResult"];
    createWalletAccountsResult?: definitions["v1CreateWalletAccountsResult"];
    initUserEmailRecoveryResult?: definitions["v1InitUserEmailRecoveryResult"];
    recoverUserResult?: definitions["v1RecoverUserResult"];
    setOrganizationFeatureResult?: definitions["v1SetOrganizationFeatureResult"];
    removeOrganizationFeatureResult?: definitions["v1RemoveOrganizationFeatureResult"];
    exportPrivateKeyResult?: definitions["v1ExportPrivateKeyResult"];
    exportWalletResult?: definitions["v1ExportWalletResult"];
    createSubOrganizationResultV4?: definitions["v1CreateSubOrganizationResultV4"];
  };
  v1RootUserParams: {
    /** @description Human-readable name for a User. */
    userName: string;
    /** @description The user's email address. */
    userEmail?: string;
    /** @description A list of API Key parameters. */
    apiKeys: definitions["v1ApiKeyParams"][];
    /** @description A list of Authenticator parameters. */
    authenticators: definitions["v1AuthenticatorParamsV2"][];
  };
  v1SelectorV2: {
    subject?: string;
    operator?: definitions["immutableactivityv1Operator"];
    targets?: string[];
  };
  v1SetOrganizationFeatureIntent: {
    /** @description Name of the feature to set */
    name: definitions["v1FeatureName"];
    /** @description Optional value for the feature. Will override existing values if feature is already set. */
    value: string;
  };
  v1SetOrganizationFeatureRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_SET_ORGANIZATION_FEATURE";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1SetOrganizationFeatureIntent"];
  };
  v1SetOrganizationFeatureResult: {
    /** @description Resulting list of organization features. */
    features: definitions["v1Feature"][];
  };
  v1SetPaymentMethodIntent: {
    /** @description The account number of the customer's credit card. */
    number: string;
    /** @description The verification digits of the customer's credit card. */
    cvv: string;
    /** @description The month that the credit card expires. */
    expiryMonth: string;
    /** @description The year that the credit card expires. */
    expiryYear: string;
    /** @description The email that will receive invoices for the credit card. */
    cardHolderEmail: string;
    /** @description The name associated with the credit card. */
    cardHolderName: string;
  };
  v1SetPaymentMethodIntentV2: {
    /** @description The id of the payment method that was created clientside. */
    paymentMethodId: string;
    /** @description The email that will receive invoices for the credit card. */
    cardHolderEmail: string;
    /** @description The name associated with the credit card. */
    cardHolderName: string;
  };
  v1SetPaymentMethodResult: {
    /** @description The last four digits of the credit card added. */
    lastFour: string;
    /** @description The name associated with the payment method. */
    cardHolderName: string;
    /** @description The email address associated with the payment method. */
    cardHolderEmail: string;
  };
  v1SignRawPayloadIntent: {
    /** @description Unique identifier for a given Private Key. */
    privateKeyId: string;
    /** @description Raw unsigned payload to be signed. */
    payload: string;
    /** @description Encoding of the `payload` string. Turnkey uses this information to convert `payload` into bytes with the correct decoder (e.g. hex, utf8). */
    encoding: definitions["immutableactivityv1PayloadEncoding"];
    /** @description Hash function to apply to payload bytes before signing. This field must be set to HASH_FUNCTION_NOT_APPLICABLE for EdDSA/ed25519 signature requests; configurable payload hashing is not supported by RFC 8032. */
    hashFunction: definitions["immutableactivityv1HashFunction"];
  };
  v1SignRawPayloadIntentV2: {
    /** @description A Wallet account address, Private Key address, or Private Key identifier. */
    signWith: string;
    /** @description Raw unsigned payload to be signed. */
    payload: string;
    /** @description Encoding of the `payload` string. Turnkey uses this information to convert `payload` into bytes with the correct decoder (e.g. hex, utf8). */
    encoding: definitions["immutableactivityv1PayloadEncoding"];
    /** @description Hash function to apply to payload bytes before signing. This field must be set to HASH_FUNCTION_NOT_APPLICABLE for EdDSA/ed25519 signature requests; configurable payload hashing is not supported by RFC 8032. */
    hashFunction: definitions["immutableactivityv1HashFunction"];
  };
  v1SignRawPayloadRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1SignRawPayloadIntentV2"];
  };
  v1SignRawPayloadResult: {
    /** @description Component of an ECSDA signature. */
    r: string;
    /** @description Component of an ECSDA signature. */
    s: string;
    /** @description Component of an ECSDA signature. */
    v: string;
  };
  v1SignTransactionIntent: {
    /** @description Unique identifier for a given Private Key. */
    privateKeyId: string;
    /** @description Raw unsigned transaction to be signed by a particular Private Key. */
    unsignedTransaction: string;
    type: definitions["v1TransactionType"];
  };
  v1SignTransactionIntentV2: {
    /** @description A Wallet account address, Private Key address, or Private Key identifier. */
    signWith: string;
    /** @description Raw unsigned transaction to be signed */
    unsignedTransaction: string;
    type: definitions["v1TransactionType"];
  };
  v1SignTransactionRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_SIGN_TRANSACTION_V2";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1SignTransactionIntentV2"];
  };
  v1SignTransactionResult: {
    signedTransaction: string;
  };
  v1SimpleClientExtensionResults: {
    appid?: boolean;
    appidExclude?: boolean;
    credProps?: definitions["v1CredPropsAuthenticationExtensionsClientOutputs"];
  };
  /** @enum {string} */
  v1TagType: "TAG_TYPE_USER" | "TAG_TYPE_PRIVATE_KEY";
  /** @enum {string} */
  v1TransactionType: "TRANSACTION_TYPE_ETHEREUM";
  v1UpdateAllowedOriginsIntent: {
    /** @description Additional origins requests are allowed from besides Turnkey origins */
    allowedOrigins: string[];
  };
  v1UpdateAllowedOriginsRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_UPDATE_ALLOWED_ORIGINS";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1UpdateAllowedOriginsIntent"];
  };
  v1UpdateAllowedOriginsResult: { [key: string]: unknown };
  v1UpdatePolicyIntent: {
    /** @description Unique identifier for a given Policy. */
    policyId: string;
    /** @description Human-readable name for a Policy. */
    policyName?: string;
    /** @description The instruction to DENY or ALLOW an activity (optional). */
    policyEffect?: definitions["immutableactivityv1Effect"];
    /** @description The condition expression that triggers the Effect (optional). */
    policyCondition?: string;
    /** @description The consensus expression that triggers the Effect (optional). */
    policyConsensus?: string;
    /** @description Accompanying notes for a Policy (optional). */
    policyNotes?: string;
  };
  v1UpdatePolicyRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_UPDATE_POLICY";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1UpdatePolicyIntent"];
  };
  v1UpdatePolicyResult: {
    /** @description Unique identifier for a given Policy. */
    policyId: string;
  };
  v1UpdatePrivateKeyTagIntent: {
    /** @description Unique identifier for a given Private Key Tag. */
    privateKeyTagId: string;
    /** @description The new, human-readable name for the tag with the given ID. */
    newPrivateKeyTagName?: string;
    /** @description A list of Private Keys IDs to add this tag to. */
    addPrivateKeyIds: string[];
    /** @description A list of Private Key IDs to remove this tag from. */
    removePrivateKeyIds: string[];
  };
  v1UpdatePrivateKeyTagRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_UPDATE_PRIVATE_KEY_TAG";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1UpdatePrivateKeyTagIntent"];
  };
  v1UpdatePrivateKeyTagResult: {
    /** @description Unique identifier for a given Private Key Tag. */
    privateKeyTagId: string;
  };
  v1UpdateRootQuorumIntent: {
    /**
     * Format: int32
     * @description The threshold of unique approvals to reach quorum.
     */
    threshold: number;
    /** @description The unique identifiers of users who comprise the quorum set. */
    userIds: string[];
  };
  v1UpdateRootQuorumRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_UPDATE_ROOT_QUORUM";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1UpdateRootQuorumIntent"];
  };
  v1UpdateRootQuorumResult: { [key: string]: unknown };
  v1UpdateUserIntent: {
    /** @description Unique identifier for a given User. */
    userId: string;
    /** @description Human-readable name for a User. */
    userName?: string;
    /** @description The user's email address. */
    userEmail?: string;
    /** @description An updated list of User Tags to apply to this User. */
    userTagIds?: string[];
  };
  v1UpdateUserRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_UPDATE_USER";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1UpdateUserIntent"];
  };
  v1UpdateUserResult: {
    /** @description A User ID. */
    userId: string;
  };
  v1UpdateUserTagIntent: {
    /** @description Unique identifier for a given User Tag. */
    userTagId: string;
    /** @description The new, human-readable name for the tag with the given ID. */
    newUserTagName?: string;
    /** @description A list of User IDs to add this tag to. */
    addUserIds: string[];
    /** @description A list of User IDs to remove this tag from. */
    removeUserIds: string[];
  };
  v1UpdateUserTagRequest: {
    /** @enum {string} */
    type: "ACTIVITY_TYPE_UPDATE_USER_TAG";
    /** @description Timestamp (in milliseconds) of the request, used to verify liveness of user requests. */
    timestampMs: string;
    /** @description Unique identifier for a given Organization. */
    organizationId: string;
    parameters: definitions["v1UpdateUserTagIntent"];
  };
  v1UpdateUserTagResult: {
    /** @description Unique identifier for a given User Tag. */
    userTagId: string;
  };
  v1User: {
    /** @description Unique identifier for a given User. */
    userId: string;
    /** @description Human-readable name for a User. */
    userName: string;
    /** @description The user's email address. */
    userEmail?: string;
    /** @description The User's permissible access method(s). */
    accessType: definitions["externaldatav1AccessType"];
    /** @description A list of Authenticator parameters. */
    authenticators: definitions["v1Authenticator"][];
    /** @description A list of API Key parameters. */
    apiKeys: definitions["v1ApiKey"][];
    /** @description A list of User Tag IDs. */
    userTags: string[];
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
  };
  v1UserParams: {
    /** @description Human-readable name for a User. */
    userName: string;
    /** @description The user's email address. */
    userEmail?: string;
    /** @description The User's permissible access method(s). */
    accessType: definitions["immutableactivityv1AccessType"];
    /** @description A list of API Key parameters. */
    apiKeys: definitions["v1ApiKeyParams"][];
    /** @description A list of Authenticator parameters. */
    authenticators: definitions["v1AuthenticatorParams"][];
    /** @description A list of User Tag IDs. */
    userTags: string[];
  };
  v1UserParamsV2: {
    /** @description Human-readable name for a User. */
    userName: string;
    /** @description The user's email address. */
    userEmail?: string;
    /** @description The User's permissible access method(s). */
    accessType: definitions["immutableactivityv1AccessType"];
    /** @description A list of API Key parameters. */
    apiKeys: definitions["v1ApiKeyParams"][];
    /** @description A list of Authenticator parameters. */
    authenticators: definitions["v1AuthenticatorParamsV2"][];
    /** @description A list of User Tag IDs. */
    userTags: string[];
  };
  v1Vote: {
    /** @description Unique identifier for a given Vote object. */
    id: string;
    /** @description Unique identifier for a given User. */
    userId: string;
    /** @description Web and/or API user within your Organization. */
    user: definitions["v1User"];
    /** @description Unique identifier for a given Activity object. */
    activityId: string;
    /** @enum {string} */
    selection: "VOTE_SELECTION_APPROVED" | "VOTE_SELECTION_REJECTED";
    /** @description The raw message being signed within a Vote. */
    message: string;
    /** @description The public component of a cryptographic key pair used to sign messages and transactions. */
    publicKey: string;
    /** @description The signature applied to a particular vote. */
    signature: string;
    /** @description Method used to produce a signature. */
    scheme: string;
    createdAt: definitions["externaldatav1Timestamp"];
  };
  v1Wallet: {
    /** @description Unique identifier for a given Wallet. */
    walletId: string;
    /** @description Human-readable name for a Wallet. */
    walletName: string;
    createdAt: definitions["externaldatav1Timestamp"];
    updatedAt: definitions["externaldatav1Timestamp"];
    /** @description True when a given Wallet is exported, false otherwise. */
    exported: boolean;
  };
  v1WalletAccountParams: {
    /** @description Cryptographic curve used to generate a wallet Account. */
    curve: definitions["immutablecommonv1Curve"];
    /** @description Path format used to generate a wallet Account. */
    pathFormat: definitions["v1PathFormat"];
    /** @description Path used to generate a wallet Account. */
    path: string;
    /** @description Address format used to generate a wallet Acccount. */
    addressFormat: definitions["immutablecommonv1AddressFormat"];
  };
  v1WalletParams: {
    /** @description Human-readable name for a Wallet. */
    walletName: string;
    /** @description A list of wallet Accounts. */
    accounts: definitions["v1WalletAccountParams"][];
  };
  v1WalletResult: {
    walletId: string;
    /** @description A list of account addresses. */
    addresses: string[];
  };
  v1WebAuthnStamp: {
    /** @description A base64 url encoded Unique identifier for a given credential. */
    credentialId: string;
    /** @description A base64 encoded payload containing metadata about the signing context and the challenge. */
    clientDataJson: string;
    /** @description A base64 encoded payload containing metadata about the authenticator. */
    authenticatorData: string;
    /** @description The base64 url encoded signature bytes contained within the WebAuthn assertion response. */
    signature: string;
  };
};

export type operations = {
  /** Get details about an Activity */
  PublicApiService_GetActivity: {
    parameters: {
      body: {
        body: definitions["v1GetActivityRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Get details about an authenticator */
  PublicApiService_GetAuthenticator: {
    parameters: {
      body: {
        body: definitions["v1GetAuthenticatorRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetAuthenticatorResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Get details about authenticators for a user */
  PublicApiService_GetAuthenticators: {
    parameters: {
      body: {
        body: definitions["v1GetAuthenticatorsRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetAuthenticatorsResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Get details about an Organization */
  PublicApiService_GetOrganization: {
    parameters: {
      body: {
        body: definitions["v1GetOrganizationRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetOrganizationResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Get details about a Policy */
  PublicApiService_GetPolicy: {
    parameters: {
      body: {
        body: definitions["v1GetPolicyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetPolicyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Get details about a Private Key */
  PublicApiService_GetPrivateKey: {
    parameters: {
      body: {
        body: definitions["v1GetPrivateKeyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetPrivateKeyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Get details about a User */
  PublicApiService_GetUser: {
    parameters: {
      body: {
        body: definitions["v1GetUserRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetUserResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** List all Activities within an Organization */
  PublicApiService_GetActivities: {
    parameters: {
      body: {
        body: definitions["v1GetActivitiesRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetActivitiesResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** List all Policies within an Organization */
  PublicApiService_GetPolicies: {
    parameters: {
      body: {
        body: definitions["v1GetPoliciesRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetPoliciesResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** List all Private Keys within an Organization */
  PublicApiService_GetPrivateKeys: {
    parameters: {
      body: {
        body: definitions["v1GetPrivateKeysRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetPrivateKeysResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** List all Users within an Organization */
  PublicApiService_GetUsers: {
    parameters: {
      body: {
        body: definitions["v1GetUsersRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetUsersResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Get basic information about your current API or WebAuthN user and their organization. Affords Sub-Organization look ups via Parent Organization for WebAuthN users. */
  PublicApiService_GetWhoami: {
    parameters: {
      body: {
        body: definitions["v1GetWhoamiRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetWhoamiResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Approve an Activity */
  PublicApiService_ApproveActivity: {
    parameters: {
      body: {
        body: definitions["v1ApproveActivityRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Add api keys to an existing User */
  PublicApiService_CreateApiKeys: {
    parameters: {
      body: {
        body: definitions["v1CreateApiKeysRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create API-only Users in an existing Organization */
  PublicApiService_CreateApiOnlyUsers: {
    parameters: {
      body: {
        body: definitions["v1CreateApiOnlyUsersRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create Authenticators to authenticate requests to Turnkey */
  PublicApiService_CreateAuthenticators: {
    parameters: {
      body: {
        body: definitions["v1CreateAuthenticatorsRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create Invitations to join an existing Organization */
  PublicApiService_CreateInvitations: {
    parameters: {
      body: {
        body: definitions["v1CreateInvitationsRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create a new Policy */
  PublicApiService_CreatePolicy: {
    parameters: {
      body: {
        body: definitions["v1CreatePolicyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create a private key tag and add it to private keys. */
  PublicApiService_CreatePrivateKeyTag: {
    parameters: {
      body: {
        body: definitions["v1CreatePrivateKeyTagRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create new Private Keys */
  PublicApiService_CreatePrivateKeys: {
    parameters: {
      body: {
        body: definitions["v1CreatePrivateKeysRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create a new Sub-Organization */
  PublicApiService_CreateSubOrganization: {
    parameters: {
      body: {
        body: definitions["v1CreateSubOrganizationRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create a user tag and add it to users. */
  PublicApiService_CreateUserTag: {
    parameters: {
      body: {
        body: definitions["v1CreateUserTagRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create Users in an existing Organization */
  PublicApiService_CreateUsers: {
    parameters: {
      body: {
        body: definitions["v1CreateUsersRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Create a Wallet and derive addresses */
  PublicApiService_CreateWallet: {
    parameters: {
      body: {
        body: definitions["v1CreateWalletRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Derive additional addresses using an existing wallet */
  PublicApiService_CreateWalletAccounts: {
    parameters: {
      body: {
        body: definitions["v1CreateWalletAccountsRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Remove api keys from a User */
  PublicApiService_DeleteApiKeys: {
    parameters: {
      body: {
        body: definitions["v1DeleteApiKeysRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Remove authenticators from a User */
  PublicApiService_DeleteAuthenticators: {
    parameters: {
      body: {
        body: definitions["v1DeleteAuthenticatorsRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Delete an existing Invitation */
  PublicApiService_DeleteInvitation: {
    parameters: {
      body: {
        body: definitions["v1DeleteInvitationRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Delete an existing Policy */
  PublicApiService_DeletePolicy: {
    parameters: {
      body: {
        body: definitions["v1DeletePolicyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Exports a Private Key */
  PublicApiService_ExportPrivateKey: {
    parameters: {
      body: {
        body: definitions["v1ExportPrivateKeyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Exports a Wallet */
  PublicApiService_ExportWallet: {
    parameters: {
      body: {
        body: definitions["v1ExportWalletRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Initializes a new email recovery */
  PublicApiService_InitUserEmailRecovery: {
    parameters: {
      body: {
        body: definitions["v1InitUserEmailRecoveryRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Completes the process of recovering a user by adding an authenticator */
  PublicApiService_RecoverUser: {
    parameters: {
      body: {
        body: definitions["v1RecoverUserRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Reject an Activity */
  PublicApiService_RejectActivity: {
    parameters: {
      body: {
        body: definitions["v1RejectActivityRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Removes an organization feature */
  PublicApiService_RemoveOrganizationFeature: {
    parameters: {
      body: {
        body: definitions["v1RemoveOrganizationFeatureRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Sets an organization feature */
  PublicApiService_SetOrganizationFeature: {
    parameters: {
      body: {
        body: definitions["v1SetOrganizationFeatureRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Sign a raw payload */
  PublicApiService_SignRawPayload: {
    parameters: {
      body: {
        body: definitions["v1SignRawPayloadRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Sign a transaction */
  PublicApiService_SignTransaction: {
    parameters: {
      body: {
        body: definitions["v1SignTransactionRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Update the allowable origins for credentials and requests */
  PublicApiService_UpdateAllowedOrigins: {
    parameters: {
      body: {
        body: definitions["v1UpdateAllowedOriginsRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Update an existing Policy */
  PublicApiService_UpdatePolicy: {
    parameters: {
      body: {
        body: definitions["v1UpdatePolicyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Update human-readable name or associated private keys. Note that this activity is atomic: all of the updates will succeed at once, or all of them will fail. */
  PublicApiService_UpdatePrivateKeyTag: {
    parameters: {
      body: {
        body: definitions["v1UpdatePrivateKeyTagRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Set the threshold and members of the root quorum. This must be approved by the current root quorum. */
  PublicApiService_UpdateRootQuorum: {
    parameters: {
      body: {
        body: definitions["v1UpdateRootQuorumRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Update a User in an existing Organization */
  PublicApiService_UpdateUser: {
    parameters: {
      body: {
        body: definitions["v1UpdateUserRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  /** Update human-readable name or associated users. Note that this activity is atomic: all of the updates will succeed at once, or all of them will fail. */
  PublicApiService_UpdateUserTag: {
    parameters: {
      body: {
        body: definitions["v1UpdateUserTagRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ActivityResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  PublicApiService_NOOPCodegenAnchor: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1NOOPCodegenAnchorResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
};

export type external = {};
