// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file com/daml/ledger/api/v2/crypto.proto (package com.daml.ledger.api.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file com/daml/ledger/api/v2/crypto.proto.
 */
export const file_com_daml_ledger_api_v2_crypto: GenFile = /*@__PURE__*/
  fileDesc("CiNjb20vZGFtbC9sZWRnZXIvYXBpL3YyL2NyeXB0by5wcm90bxIWY29tLmRhbWwubGVkZ2VyLmFwaS52MiKXAQoQU2lnbmluZ1B1YmxpY0tleRI3CgZmb3JtYXQYASABKA4yJy5jb20uZGFtbC5sZWRnZXIuYXBpLnYyLkNyeXB0b0tleUZvcm1hdBIQCghrZXlfZGF0YRgCIAEoDBI4CghrZXlfc3BlYxgDIAEoDjImLmNvbS5kYW1sLmxlZGdlci5hcGkudjIuU2lnbmluZ0tleVNwZWMiuAEKCVNpZ25hdHVyZRI3CgZmb3JtYXQYASABKA4yJy5jb20uZGFtbC5sZWRnZXIuYXBpLnYyLlNpZ25hdHVyZUZvcm1hdBIRCglzaWduYXR1cmUYAiABKAwSEQoJc2lnbmVkX2J5GAMgASgJEkwKFnNpZ25pbmdfYWxnb3JpdGhtX3NwZWMYBCABKA4yLC5jb20uZGFtbC5sZWRnZXIuYXBpLnYyLlNpZ25pbmdBbGdvcml0aG1TcGVjKrUBCg5TaWduaW5nS2V5U3BlYxIgChxTSUdOSU5HX0tFWV9TUEVDX1VOU1BFQ0lGSUVEEAASIgoeU0lHTklOR19LRVlfU1BFQ19FQ19DVVJWRTI1NTE5EAESHAoYU0lHTklOR19LRVlfU1BFQ19FQ19QMjU2EAISHAoYU0lHTklOR19LRVlfU1BFQ19FQ19QMzg0EAMSIQodU0lHTklOR19LRVlfU1BFQ19FQ19TRUNQMjU2SzEQBCqqAQoPQ3J5cHRvS2V5Rm9ybWF0EiEKHUNSWVBUT19LRVlfRk9STUFUX1VOU1BFQ0lGSUVEEAASGQoVQ1JZUFRPX0tFWV9GT1JNQVRfREVSEAESGQoVQ1JZUFRPX0tFWV9GT1JNQVRfUkFXEAISNgoyQ1JZUFRPX0tFWV9GT1JNQVRfREVSX1g1MDlfU1VCSkVDVF9QVUJMSUNfS0VZX0lORk8QAyIGCJBOEJBOKrgBChRTaWduaW5nQWxnb3JpdGhtU3BlYxImCiJTSUdOSU5HX0FMR09SSVRITV9TUEVDX1VOU1BFQ0lGSUVEEAASIgoeU0lHTklOR19BTEdPUklUSE1fU1BFQ19FRDI1NTE5EAESKQolU0lHTklOR19BTEdPUklUSE1fU1BFQ19FQ19EU0FfU0hBXzI1NhACEikKJVNJR05JTkdfQUxHT1JJVEhNX1NQRUNfRUNfRFNBX1NIQV8zODQQAyqkAQoPU2lnbmF0dXJlRm9ybWF0EiAKHFNJR05BVFVSRV9GT1JNQVRfVU5TUEVDSUZJRUQQABIYChRTSUdOQVRVUkVfRk9STUFUX1JBVxABEhgKFFNJR05BVFVSRV9GT1JNQVRfREVSEAISGwoXU0lHTkFUVVJFX0ZPUk1BVF9DT05DQVQQAxIeChlTSUdOQVRVUkVfRk9STUFUX1NZTUJPTElDEJBOQkMKFmNvbS5kYW1sLmxlZGdlci5hcGkudjJCEENyeXB0b091dGVyQ2xhc3OqAhZDb20uRGFtbC5MZWRnZXIuQXBpLlYyYgZwcm90bzM");

/**
 * @generated from message com.daml.ledger.api.v2.SigningPublicKey
 */
export type SigningPublicKey = Message<"com.daml.ledger.api.v2.SigningPublicKey"> & {
  /**
   * The serialization format of the public key
   *
   * Required
   *
   * @generated from field: com.daml.ledger.api.v2.CryptoKeyFormat format = 1;
   */
  format: CryptoKeyFormat;

  /**
   * Serialized public key in the format specified above
   *
   * Required: must be non-empty
   *
   * @generated from field: bytes key_data = 2;
   */
  keyData: Uint8Array;

  /**
   * The key specification
   *
   * Required
   *
   * @generated from field: com.daml.ledger.api.v2.SigningKeySpec key_spec = 3;
   */
  keySpec: SigningKeySpec;
};

/**
 * Describes the message com.daml.ledger.api.v2.SigningPublicKey.
 * Use `create(SigningPublicKeySchema)` to create a new message.
 */
export const SigningPublicKeySchema: GenMessage<SigningPublicKey> = /*@__PURE__*/
  messageDesc(file_com_daml_ledger_api_v2_crypto, 0);

/**
 * @generated from message com.daml.ledger.api.v2.Signature
 */
export type Signature = Message<"com.daml.ledger.api.v2.Signature"> & {
  /**
   * Required
   *
   * @generated from field: com.daml.ledger.api.v2.SignatureFormat format = 1;
   */
  format: SignatureFormat;

  /**
   * Required: must be non-empty
   *
   * @generated from field: bytes signature = 2;
   */
  signature: Uint8Array;

  /**
   * The fingerprint/id of the keypair used to create this signature and needed to verify.
   *
   * Required
   *
   * @generated from field: string signed_by = 3;
   */
  signedBy: string;

  /**
   * The signing algorithm specification used to produce this signature
   *
   * Required
   *
   * @generated from field: com.daml.ledger.api.v2.SigningAlgorithmSpec signing_algorithm_spec = 4;
   */
  signingAlgorithmSpec: SigningAlgorithmSpec;
};

/**
 * Describes the message com.daml.ledger.api.v2.Signature.
 * Use `create(SignatureSchema)` to create a new message.
 */
export const SignatureSchema: GenMessage<Signature> = /*@__PURE__*/
  messageDesc(file_com_daml_ledger_api_v2_crypto, 1);

/**
 * @generated from enum com.daml.ledger.api.v2.SigningKeySpec
 */
export enum SigningKeySpec {
  /**
   * @generated from enum value: SIGNING_KEY_SPEC_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Elliptic Curve Key from Curve25519
   * as defined in http://ed25519.cr.yp.to/
   *
   * @generated from enum value: SIGNING_KEY_SPEC_EC_CURVE25519 = 1;
   */
  EC_CURVE25519 = 1,

  /**
   * Elliptic Curve Key from the NIST P-256 curve (aka secp256r1)
   * as defined in https://doi.org/10.6028/NIST.FIPS.186-4
   *
   * @generated from enum value: SIGNING_KEY_SPEC_EC_P256 = 2;
   */
  EC_P256 = 2,

  /**
   * Elliptic Curve Key from the NIST P-384 curve (aka secp384r1)
   * as defined in https://doi.org/10.6028/NIST.FIPS.186-4
   *
   * @generated from enum value: SIGNING_KEY_SPEC_EC_P384 = 3;
   */
  EC_P384 = 3,

  /**
   * Elliptic Curve Key from SECG P256k1 curve (aka secp256k1)
   * commonly used in bitcoin and ethereum
   * as defined in https://www.secg.org/sec2-v2.pdf
   *
   * @generated from enum value: SIGNING_KEY_SPEC_EC_SECP256K1 = 4;
   */
  EC_SECP256K1 = 4,
}

/**
 * Describes the enum com.daml.ledger.api.v2.SigningKeySpec.
 */
export const SigningKeySpecSchema: GenEnum<SigningKeySpec> = /*@__PURE__*/
  enumDesc(file_com_daml_ledger_api_v2_crypto, 0);

/**
 * Serialization format for crypto keys and signatures
 *
 * @generated from enum com.daml.ledger.api.v2.CryptoKeyFormat
 */
export enum CryptoKeyFormat {
  /**
   * @generated from enum value: CRYPTO_KEY_FORMAT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * ASN.1 + DER encoding
   * Legacy format no longer used, except for migrations
   *
   * @generated from enum value: CRYPTO_KEY_FORMAT_DER = 1;
   */
  DER = 1,

  /**
   * Raw encoding of a key
   *
   * @generated from enum value: CRYPTO_KEY_FORMAT_RAW = 2;
   */
  RAW = 2,

  /**
   * ASN.1 + DER-encoding of X.509 SubjectPublicKeyInfo structure: https://datatracker.ietf.org/doc/html/rfc5280#section-4.1
   *
   * @generated from enum value: CRYPTO_KEY_FORMAT_DER_X509_SUBJECT_PUBLIC_KEY_INFO = 3;
   */
  DER_X509_SUBJECT_PUBLIC_KEY_INFO = 3,
}

/**
 * Describes the enum com.daml.ledger.api.v2.CryptoKeyFormat.
 */
export const CryptoKeyFormatSchema: GenEnum<CryptoKeyFormat> = /*@__PURE__*/
  enumDesc(file_com_daml_ledger_api_v2_crypto, 1);

/**
 * @generated from enum com.daml.ledger.api.v2.SigningAlgorithmSpec
 */
export enum SigningAlgorithmSpec {
  /**
   * @generated from enum value: SIGNING_ALGORITHM_SPEC_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * EdDSA Signature based on Curve25519 with SHA-512
   * http://ed25519.cr.yp.to/
   *
   * @generated from enum value: SIGNING_ALGORITHM_SPEC_ED25519 = 1;
   */
  ED25519 = 1,

  /**
   * Elliptic Curve Digital Signature Algorithm with SHA256
   *
   * @generated from enum value: SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256 = 2;
   */
  EC_DSA_SHA_256 = 2,

  /**
   * Elliptic Curve Digital Signature Algorithm with SHA384
   *
   * @generated from enum value: SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384 = 3;
   */
  EC_DSA_SHA_384 = 3,
}

/**
 * Describes the enum com.daml.ledger.api.v2.SigningAlgorithmSpec.
 */
export const SigningAlgorithmSpecSchema: GenEnum<SigningAlgorithmSpec> = /*@__PURE__*/
  enumDesc(file_com_daml_ledger_api_v2_crypto, 2);

/**
 * @generated from enum com.daml.ledger.api.v2.SignatureFormat
 */
export enum SignatureFormat {
  /**
   * @generated from enum value: SIGNATURE_FORMAT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Signature scheme specific signature format
   * Legacy format no longer used, except for migrations
   *
   * @generated from enum value: SIGNATURE_FORMAT_RAW = 1;
   */
  RAW = 1,

  /**
   * ASN.1 + DER-encoding of the `r` and `s` integers, as defined in https://datatracker.ietf.org/doc/html/rfc3279#section-2.2.3
   * Used for ECDSA signatures
   *
   * @generated from enum value: SIGNATURE_FORMAT_DER = 2;
   */
  DER = 2,

  /**
   * Concatenation of the integers `r || s` in little-endian form, as defined in https://datatracker.ietf.org/doc/html/rfc8032#section-3.3
   * Note that this is different from the format defined in IEEE P1363, which uses concatenation in big-endian form.
   * Used for EdDSA signatures
   *
   * @generated from enum value: SIGNATURE_FORMAT_CONCAT = 3;
   */
  CONCAT = 3,

  /**
   * Symbolic crypto, must only be used for testing
   *
   * @generated from enum value: SIGNATURE_FORMAT_SYMBOLIC = 10000;
   */
  SYMBOLIC = 10000,
}

/**
 * Describes the enum com.daml.ledger.api.v2.SignatureFormat.
 */
export const SignatureFormatSchema: GenEnum<SignatureFormat> = /*@__PURE__*/
  enumDesc(file_com_daml_ledger_api_v2_crypto, 3);

