export const SIGNATURE_SCHEME_TK_API_SECP256K1 =
  "SIGNATURE_SCHEME_TK_API_SECP256K1";
export const SIGNATURE_SCHEME_TK_API_ED25519 =
  "SIGNATURE_SCHEME_TK_API_ED25519";
export const WALLET_TYPE_EVM = "evm";
export const WALLET_TYPE_SOLANA = "solana";
export const STAMP_HEADER_NAME = "X-Stamp";
