export const SIGNATURE_SCHEME_TK_API_SECP256K1_ERC191 =
  "SIGNATURE_SCHEME_TK_API_SECP256K1_ERC191";
export const SIGNATURE_SCHEME_TK_API_ED25519 =
  "SIGNATURE_SCHEME_TK_API_ED25519";
export const WALLET_TYPE_EVM = "evm" as const;
export const WALLET_TYPE_SOLANA = "solana" as const;
export const STAMP_HEADER_NAME = "X-Stamp";
