/* @generated by codegen. DO NOT EDIT BY HAND */

import {
  TERMINAL_ACTIVITY_STATUSES,
  TActivityResponse,
  TActivityStatus,
  TSignedRequest,
} from "@turnkey/http";

import type { definitions } from "../__inputs__/public_api.types";

import {
  GrpcStatus,
  TurnkeyRequestError,
  TurnkeySDKClientConfig,
} from "../__types__/base";

import { VERSION } from "../__generated__/version";

import type * as SdkApiTypes from "./sdk_api_types";

export class TurnkeySDKClientBase {
  config: TurnkeySDKClientConfig;

  constructor(config: TurnkeySDKClientConfig) {
    this.config = config;
  }

  async request<TBodyType, TResponseType>(
    url: string,
    body: TBodyType
  ): Promise<TResponseType> {
    const fullUrl = this.config.apiBaseUrl + url;
    const stringifiedBody = JSON.stringify(body);
    const stamp = await this.config.stamper.stamp(stringifiedBody);

    const response = await fetch(fullUrl, {
      method: "POST",
      headers: {
        [stamp.stampHeaderName]: stamp.stampHeaderValue,
        "X-Client-Version": VERSION,
      },
      body: stringifiedBody,
      redirect: "follow",
    });

    if (!response.ok) {
      let res: GrpcStatus;
      try {
        res = await response.json();
      } catch (_) {
        throw new Error(`${response.status} ${response.statusText}`);
      }

      throw new TurnkeyRequestError(res);
    }

    const data = await response.json();
    return data as TResponseType;
  }

  async command<TBodyType, TResponseType>(
    url: string,
    body: TBodyType,
    resultKey: string
  ): Promise<TResponseType> {
    const pollingDuration = this.config.activityPoller?.intervalMs ?? 1000;
    const maxRetries = this.config.activityPoller?.numRetries ?? 3;

    const sleep = (ms: number) =>
      new Promise((resolve) => setTimeout(resolve, ms));

    const handleResponse = (activityData: TActivityResponse): TResponseType => {
      const { result, status } = activityData.activity;

      if (status === "ACTIVITY_STATUS_COMPLETED") {
        return {
          ...result[`${resultKey}` as keyof definitions["v1Result"]],
          ...activityData,
        } as TResponseType;
      }

      return activityData as TResponseType;
    };

    let attempts = 0;

    const pollStatus = async (activityId: string): Promise<TResponseType> => {
      const pollBody = { activityId };
      const pollData = (await this.getActivity(pollBody)) as TActivityResponse;

      if (attempts > maxRetries) {
        return handleResponse(pollData);
      }

      attempts += 1;

      if (
        !TERMINAL_ACTIVITY_STATUSES.includes(
          pollData.activity.status as TActivityStatus
        )
      ) {
        await sleep(pollingDuration);
        return pollStatus(activityId);
      }

      return handleResponse(pollData);
    };

    const responseData = (await this.request<TBodyType, TResponseType>(
      url,
      body
    )) as TActivityResponse;

    if (
      !TERMINAL_ACTIVITY_STATUSES.includes(
        responseData.activity.status as TActivityStatus
      )
    ) {
      return pollStatus(responseData.activity.id);
    }

    return handleResponse(responseData);
  }

  async activityDecision<TBodyType, TResponseType>(
    url: string,
    body: TBodyType
  ): Promise<TResponseType> {
    const activityData = (await this.request(url, body)) as TActivityResponse;

    return {
      ...activityData["activity"]["result"],
      ...activityData,
    } as TResponseType;
  }

  getActivity = async (
    input: SdkApiTypes.TGetActivityBody
  ): Promise<SdkApiTypes.TGetActivityResponse> => {
    return this.request("/public/v1/query/get_activity", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetActivity = async (
    input: SdkApiTypes.TGetActivityBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/get_activity";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getApiKey = async (
    input: SdkApiTypes.TGetApiKeyBody
  ): Promise<SdkApiTypes.TGetApiKeyResponse> => {
    return this.request("/public/v1/query/get_api_key", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetApiKey = async (
    input: SdkApiTypes.TGetApiKeyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/get_api_key";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getApiKeys = async (
    input: SdkApiTypes.TGetApiKeysBody = {}
  ): Promise<SdkApiTypes.TGetApiKeysResponse> => {
    return this.request("/public/v1/query/get_api_keys", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetApiKeys = async (
    input: SdkApiTypes.TGetApiKeysBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/get_api_keys";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getAttestationDocument = async (
    input: SdkApiTypes.TGetAttestationDocumentBody
  ): Promise<SdkApiTypes.TGetAttestationDocumentResponse> => {
    return this.request("/public/v1/query/get_attestation", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetAttestationDocument = async (
    input: SdkApiTypes.TGetAttestationDocumentBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/get_attestation";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getAuthenticator = async (
    input: SdkApiTypes.TGetAuthenticatorBody
  ): Promise<SdkApiTypes.TGetAuthenticatorResponse> => {
    return this.request("/public/v1/query/get_authenticator", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetAuthenticator = async (
    input: SdkApiTypes.TGetAuthenticatorBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/query/get_authenticator";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getAuthenticators = async (
    input: SdkApiTypes.TGetAuthenticatorsBody
  ): Promise<SdkApiTypes.TGetAuthenticatorsResponse> => {
    return this.request("/public/v1/query/get_authenticators", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetAuthenticators = async (
    input: SdkApiTypes.TGetAuthenticatorsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/query/get_authenticators";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getOauthProviders = async (
    input: SdkApiTypes.TGetOauthProvidersBody
  ): Promise<SdkApiTypes.TGetOauthProvidersResponse> => {
    return this.request("/public/v1/query/get_oauth_providers", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetOauthProviders = async (
    input: SdkApiTypes.TGetOauthProvidersBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/query/get_oauth_providers";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getOrganization = async (
    input: SdkApiTypes.TGetOrganizationBody = {}
  ): Promise<SdkApiTypes.TGetOrganizationResponse> => {
    return this.request("/public/v1/query/get_organization", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetOrganization = async (
    input: SdkApiTypes.TGetOrganizationBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/query/get_organization";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getOrganizationConfigs = async (
    input: SdkApiTypes.TGetOrganizationConfigsBody
  ): Promise<SdkApiTypes.TGetOrganizationConfigsResponse> => {
    return this.request("/public/v1/query/get_organization_configs", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetOrganizationConfigs = async (
    input: SdkApiTypes.TGetOrganizationConfigsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/query/get_organization_configs";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getPolicy = async (
    input: SdkApiTypes.TGetPolicyBody
  ): Promise<SdkApiTypes.TGetPolicyResponse> => {
    return this.request("/public/v1/query/get_policy", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetPolicy = async (
    input: SdkApiTypes.TGetPolicyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/get_policy";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getPrivateKey = async (
    input: SdkApiTypes.TGetPrivateKeyBody
  ): Promise<SdkApiTypes.TGetPrivateKeyResponse> => {
    return this.request("/public/v1/query/get_private_key", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetPrivateKey = async (
    input: SdkApiTypes.TGetPrivateKeyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/get_private_key";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getUser = async (
    input: SdkApiTypes.TGetUserBody
  ): Promise<SdkApiTypes.TGetUserResponse> => {
    return this.request("/public/v1/query/get_user", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetUser = async (
    input: SdkApiTypes.TGetUserBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/get_user";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getWallet = async (
    input: SdkApiTypes.TGetWalletBody
  ): Promise<SdkApiTypes.TGetWalletResponse> => {
    return this.request("/public/v1/query/get_wallet", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetWallet = async (
    input: SdkApiTypes.TGetWalletBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/get_wallet";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getActivities = async (
    input: SdkApiTypes.TGetActivitiesBody = {}
  ): Promise<SdkApiTypes.TGetActivitiesResponse> => {
    return this.request("/public/v1/query/list_activities", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetActivities = async (
    input: SdkApiTypes.TGetActivitiesBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/list_activities";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getPolicies = async (
    input: SdkApiTypes.TGetPoliciesBody = {}
  ): Promise<SdkApiTypes.TGetPoliciesResponse> => {
    return this.request("/public/v1/query/list_policies", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetPolicies = async (
    input: SdkApiTypes.TGetPoliciesBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/list_policies";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  listPrivateKeyTags = async (
    input: SdkApiTypes.TListPrivateKeyTagsBody
  ): Promise<SdkApiTypes.TListPrivateKeyTagsResponse> => {
    return this.request("/public/v1/query/list_private_key_tags", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampListPrivateKeyTags = async (
    input: SdkApiTypes.TListPrivateKeyTagsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/query/list_private_key_tags";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getPrivateKeys = async (
    input: SdkApiTypes.TGetPrivateKeysBody = {}
  ): Promise<SdkApiTypes.TGetPrivateKeysResponse> => {
    return this.request("/public/v1/query/list_private_keys", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetPrivateKeys = async (
    input: SdkApiTypes.TGetPrivateKeysBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/query/list_private_keys";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getSubOrgIds = async (
    input: SdkApiTypes.TGetSubOrgIdsBody = {}
  ): Promise<SdkApiTypes.TGetSubOrgIdsResponse> => {
    return this.request("/public/v1/query/list_suborgs", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetSubOrgIds = async (
    input: SdkApiTypes.TGetSubOrgIdsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/list_suborgs";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  listUserTags = async (
    input: SdkApiTypes.TListUserTagsBody = {}
  ): Promise<SdkApiTypes.TListUserTagsResponse> => {
    return this.request("/public/v1/query/list_user_tags", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampListUserTags = async (
    input: SdkApiTypes.TListUserTagsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/list_user_tags";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getUsers = async (
    input: SdkApiTypes.TGetUsersBody = {}
  ): Promise<SdkApiTypes.TGetUsersResponse> => {
    return this.request("/public/v1/query/list_users", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetUsers = async (
    input: SdkApiTypes.TGetUsersBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/list_users";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getWalletAccounts = async (
    input: SdkApiTypes.TGetWalletAccountsBody
  ): Promise<SdkApiTypes.TGetWalletAccountsResponse> => {
    return this.request("/public/v1/query/list_wallet_accounts", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetWalletAccounts = async (
    input: SdkApiTypes.TGetWalletAccountsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/query/list_wallet_accounts";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getWallets = async (
    input: SdkApiTypes.TGetWalletsBody = {}
  ): Promise<SdkApiTypes.TGetWalletsResponse> => {
    return this.request("/public/v1/query/list_wallets", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetWallets = async (
    input: SdkApiTypes.TGetWalletsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/list_wallets";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  getWhoami = async (
    input: SdkApiTypes.TGetWhoamiBody = {}
  ): Promise<SdkApiTypes.TGetWhoamiResponse> => {
    return this.request("/public/v1/query/whoami", {
      ...input,
      organizationId: input.organizationId ?? this.config.organizationId,
    });
  };

  stampGetWhoami = async (
    input: SdkApiTypes.TGetWhoamiBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/query/whoami";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  approveActivity = async (
    input: SdkApiTypes.TApproveActivityBody
  ): Promise<SdkApiTypes.TApproveActivityResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.activityDecision("/public/v1/submit/approve_activity", {
      parameters: rest,
      organizationId: organizationId ?? this.config.organizationId,
      timestampMs: timestampMs ?? String(Date.now()),
      type: "ACTIVITY_TYPE_APPROVE_ACTIVITY",
    });
  };

  stampApproveActivity = async (
    input: SdkApiTypes.TApproveActivityBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/approve_activity";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createApiKeys = async (
    input: SdkApiTypes.TCreateApiKeysBody
  ): Promise<SdkApiTypes.TCreateApiKeysResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_api_keys",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_API_KEYS_V2",
      },
      "createApiKeysResult"
    );
  };

  stampCreateApiKeys = async (
    input: SdkApiTypes.TCreateApiKeysBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_api_keys";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createApiOnlyUsers = async (
    input: SdkApiTypes.TCreateApiOnlyUsersBody
  ): Promise<SdkApiTypes.TCreateApiOnlyUsersResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_api_only_users",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_API_ONLY_USERS",
      },
      "createApiOnlyUsersResult"
    );
  };

  stampCreateApiOnlyUsers = async (
    input: SdkApiTypes.TCreateApiOnlyUsersBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_api_only_users";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createAuthenticators = async (
    input: SdkApiTypes.TCreateAuthenticatorsBody
  ): Promise<SdkApiTypes.TCreateAuthenticatorsResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_authenticators",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2",
      },
      "createAuthenticatorsResult"
    );
  };

  stampCreateAuthenticators = async (
    input: SdkApiTypes.TCreateAuthenticatorsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_authenticators";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createInvitations = async (
    input: SdkApiTypes.TCreateInvitationsBody
  ): Promise<SdkApiTypes.TCreateInvitationsResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_invitations",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_INVITATIONS",
      },
      "createInvitationsResult"
    );
  };

  stampCreateInvitations = async (
    input: SdkApiTypes.TCreateInvitationsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_invitations";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createOauthProviders = async (
    input: SdkApiTypes.TCreateOauthProvidersBody
  ): Promise<SdkApiTypes.TCreateOauthProvidersResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_oauth_providers",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_OAUTH_PROVIDERS",
      },
      "createOauthProvidersResult"
    );
  };

  stampCreateOauthProviders = async (
    input: SdkApiTypes.TCreateOauthProvidersBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_oauth_providers";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createPolicies = async (
    input: SdkApiTypes.TCreatePoliciesBody
  ): Promise<SdkApiTypes.TCreatePoliciesResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_policies",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_POLICIES",
      },
      "createPoliciesResult"
    );
  };

  stampCreatePolicies = async (
    input: SdkApiTypes.TCreatePoliciesBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_policies";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createPolicy = async (
    input: SdkApiTypes.TCreatePolicyBody
  ): Promise<SdkApiTypes.TCreatePolicyResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_policy",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_POLICY_V3",
      },
      "createPolicyResult"
    );
  };

  stampCreatePolicy = async (
    input: SdkApiTypes.TCreatePolicyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/create_policy";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createPrivateKeyTag = async (
    input: SdkApiTypes.TCreatePrivateKeyTagBody
  ): Promise<SdkApiTypes.TCreatePrivateKeyTagResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_private_key_tag",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_PRIVATE_KEY_TAG",
      },
      "createPrivateKeyTagResult"
    );
  };

  stampCreatePrivateKeyTag = async (
    input: SdkApiTypes.TCreatePrivateKeyTagBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_private_key_tag";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createPrivateKeys = async (
    input: SdkApiTypes.TCreatePrivateKeysBody
  ): Promise<SdkApiTypes.TCreatePrivateKeysResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_private_keys",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2",
      },
      "createPrivateKeysResultV2"
    );
  };

  stampCreatePrivateKeys = async (
    input: SdkApiTypes.TCreatePrivateKeysBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_private_keys";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createReadOnlySession = async (
    input: SdkApiTypes.TCreateReadOnlySessionBody
  ): Promise<SdkApiTypes.TCreateReadOnlySessionResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_read_only_session",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_READ_ONLY_SESSION",
      },
      "createReadOnlySessionResult"
    );
  };

  stampCreateReadOnlySession = async (
    input: SdkApiTypes.TCreateReadOnlySessionBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_read_only_session";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createReadWriteSession = async (
    input: SdkApiTypes.TCreateReadWriteSessionBody
  ): Promise<SdkApiTypes.TCreateReadWriteSessionResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_read_write_session",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION_V2",
      },
      "createReadWriteSessionResultV2"
    );
  };

  stampCreateReadWriteSession = async (
    input: SdkApiTypes.TCreateReadWriteSessionBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_read_write_session";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createSubOrganization = async (
    input: SdkApiTypes.TCreateSubOrganizationBody
  ): Promise<SdkApiTypes.TCreateSubOrganizationResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_sub_organization",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V7",
      },
      "createSubOrganizationResultV7"
    );
  };

  stampCreateSubOrganization = async (
    input: SdkApiTypes.TCreateSubOrganizationBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_sub_organization";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createUserTag = async (
    input: SdkApiTypes.TCreateUserTagBody
  ): Promise<SdkApiTypes.TCreateUserTagResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_user_tag",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_USER_TAG",
      },
      "createUserTagResult"
    );
  };

  stampCreateUserTag = async (
    input: SdkApiTypes.TCreateUserTagBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_user_tag";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createUsers = async (
    input: SdkApiTypes.TCreateUsersBody
  ): Promise<SdkApiTypes.TCreateUsersResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_users",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_USERS_V2",
      },
      "createUsersResult"
    );
  };

  stampCreateUsers = async (
    input: SdkApiTypes.TCreateUsersBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/create_users";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createWallet = async (
    input: SdkApiTypes.TCreateWalletBody
  ): Promise<SdkApiTypes.TCreateWalletResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_wallet",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_WALLET",
      },
      "createWalletResult"
    );
  };

  stampCreateWallet = async (
    input: SdkApiTypes.TCreateWalletBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/create_wallet";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  createWalletAccounts = async (
    input: SdkApiTypes.TCreateWalletAccountsBody
  ): Promise<SdkApiTypes.TCreateWalletAccountsResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/create_wallet_accounts",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_CREATE_WALLET_ACCOUNTS",
      },
      "createWalletAccountsResult"
    );
  };

  stampCreateWalletAccounts = async (
    input: SdkApiTypes.TCreateWalletAccountsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/create_wallet_accounts";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deleteApiKeys = async (
    input: SdkApiTypes.TDeleteApiKeysBody
  ): Promise<SdkApiTypes.TDeleteApiKeysResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_api_keys",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_API_KEYS",
      },
      "deleteApiKeysResult"
    );
  };

  stampDeleteApiKeys = async (
    input: SdkApiTypes.TDeleteApiKeysBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/delete_api_keys";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deleteAuthenticators = async (
    input: SdkApiTypes.TDeleteAuthenticatorsBody
  ): Promise<SdkApiTypes.TDeleteAuthenticatorsResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_authenticators",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_AUTHENTICATORS",
      },
      "deleteAuthenticatorsResult"
    );
  };

  stampDeleteAuthenticators = async (
    input: SdkApiTypes.TDeleteAuthenticatorsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/delete_authenticators";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deleteInvitation = async (
    input: SdkApiTypes.TDeleteInvitationBody
  ): Promise<SdkApiTypes.TDeleteInvitationResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_invitation",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_INVITATION",
      },
      "deleteInvitationResult"
    );
  };

  stampDeleteInvitation = async (
    input: SdkApiTypes.TDeleteInvitationBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/delete_invitation";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deleteOauthProviders = async (
    input: SdkApiTypes.TDeleteOauthProvidersBody
  ): Promise<SdkApiTypes.TDeleteOauthProvidersResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_oauth_providers",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_OAUTH_PROVIDERS",
      },
      "deleteOauthProvidersResult"
    );
  };

  stampDeleteOauthProviders = async (
    input: SdkApiTypes.TDeleteOauthProvidersBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/delete_oauth_providers";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deletePolicy = async (
    input: SdkApiTypes.TDeletePolicyBody
  ): Promise<SdkApiTypes.TDeletePolicyResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_policy",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_POLICY",
      },
      "deletePolicyResult"
    );
  };

  stampDeletePolicy = async (
    input: SdkApiTypes.TDeletePolicyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/delete_policy";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deletePrivateKeyTags = async (
    input: SdkApiTypes.TDeletePrivateKeyTagsBody
  ): Promise<SdkApiTypes.TDeletePrivateKeyTagsResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_private_key_tags",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_PRIVATE_KEY_TAGS",
      },
      "deletePrivateKeyTagsResult"
    );
  };

  stampDeletePrivateKeyTags = async (
    input: SdkApiTypes.TDeletePrivateKeyTagsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/delete_private_key_tags";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deletePrivateKeys = async (
    input: SdkApiTypes.TDeletePrivateKeysBody
  ): Promise<SdkApiTypes.TDeletePrivateKeysResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_private_keys",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_PRIVATE_KEYS",
      },
      "deletePrivateKeysResult"
    );
  };

  stampDeletePrivateKeys = async (
    input: SdkApiTypes.TDeletePrivateKeysBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/delete_private_keys";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deleteSubOrganization = async (
    input: SdkApiTypes.TDeleteSubOrganizationBody
  ): Promise<SdkApiTypes.TDeleteSubOrganizationResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_sub_organization",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_SUB_ORGANIZATION",
      },
      "deleteSubOrganizationResult"
    );
  };

  stampDeleteSubOrganization = async (
    input: SdkApiTypes.TDeleteSubOrganizationBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/delete_sub_organization";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deleteUserTags = async (
    input: SdkApiTypes.TDeleteUserTagsBody
  ): Promise<SdkApiTypes.TDeleteUserTagsResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_user_tags",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_USER_TAGS",
      },
      "deleteUserTagsResult"
    );
  };

  stampDeleteUserTags = async (
    input: SdkApiTypes.TDeleteUserTagsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/delete_user_tags";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deleteUsers = async (
    input: SdkApiTypes.TDeleteUsersBody
  ): Promise<SdkApiTypes.TDeleteUsersResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_users",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_USERS",
      },
      "deleteUsersResult"
    );
  };

  stampDeleteUsers = async (
    input: SdkApiTypes.TDeleteUsersBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/delete_users";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  deleteWallets = async (
    input: SdkApiTypes.TDeleteWalletsBody
  ): Promise<SdkApiTypes.TDeleteWalletsResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/delete_wallets",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_DELETE_WALLETS",
      },
      "deleteWalletsResult"
    );
  };

  stampDeleteWallets = async (
    input: SdkApiTypes.TDeleteWalletsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/delete_wallets";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  emailAuth = async (
    input: SdkApiTypes.TEmailAuthBody
  ): Promise<SdkApiTypes.TEmailAuthResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/email_auth",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_EMAIL_AUTH_V2",
      },
      "emailAuthResult"
    );
  };

  stampEmailAuth = async (
    input: SdkApiTypes.TEmailAuthBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/email_auth";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  exportPrivateKey = async (
    input: SdkApiTypes.TExportPrivateKeyBody
  ): Promise<SdkApiTypes.TExportPrivateKeyResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/export_private_key",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_EXPORT_PRIVATE_KEY",
      },
      "exportPrivateKeyResult"
    );
  };

  stampExportPrivateKey = async (
    input: SdkApiTypes.TExportPrivateKeyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/export_private_key";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  exportWallet = async (
    input: SdkApiTypes.TExportWalletBody
  ): Promise<SdkApiTypes.TExportWalletResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/export_wallet",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_EXPORT_WALLET",
      },
      "exportWalletResult"
    );
  };

  stampExportWallet = async (
    input: SdkApiTypes.TExportWalletBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/export_wallet";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  exportWalletAccount = async (
    input: SdkApiTypes.TExportWalletAccountBody
  ): Promise<SdkApiTypes.TExportWalletAccountResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/export_wallet_account",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_EXPORT_WALLET_ACCOUNT",
      },
      "exportWalletAccountResult"
    );
  };

  stampExportWalletAccount = async (
    input: SdkApiTypes.TExportWalletAccountBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/export_wallet_account";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  importPrivateKey = async (
    input: SdkApiTypes.TImportPrivateKeyBody
  ): Promise<SdkApiTypes.TImportPrivateKeyResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/import_private_key",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_IMPORT_PRIVATE_KEY",
      },
      "importPrivateKeyResult"
    );
  };

  stampImportPrivateKey = async (
    input: SdkApiTypes.TImportPrivateKeyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/import_private_key";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  importWallet = async (
    input: SdkApiTypes.TImportWalletBody
  ): Promise<SdkApiTypes.TImportWalletResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/import_wallet",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_IMPORT_WALLET",
      },
      "importWalletResult"
    );
  };

  stampImportWallet = async (
    input: SdkApiTypes.TImportWalletBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/import_wallet";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  initImportPrivateKey = async (
    input: SdkApiTypes.TInitImportPrivateKeyBody
  ): Promise<SdkApiTypes.TInitImportPrivateKeyResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/init_import_private_key",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_INIT_IMPORT_PRIVATE_KEY",
      },
      "initImportPrivateKeyResult"
    );
  };

  stampInitImportPrivateKey = async (
    input: SdkApiTypes.TInitImportPrivateKeyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/init_import_private_key";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  initImportWallet = async (
    input: SdkApiTypes.TInitImportWalletBody
  ): Promise<SdkApiTypes.TInitImportWalletResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/init_import_wallet",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_INIT_IMPORT_WALLET",
      },
      "initImportWalletResult"
    );
  };

  stampInitImportWallet = async (
    input: SdkApiTypes.TInitImportWalletBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/init_import_wallet";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  initOtpAuth = async (
    input: SdkApiTypes.TInitOtpAuthBody
  ): Promise<SdkApiTypes.TInitOtpAuthResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/init_otp_auth",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_INIT_OTP_AUTH",
      },
      "initOtpAuthResult"
    );
  };

  stampInitOtpAuth = async (
    input: SdkApiTypes.TInitOtpAuthBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/init_otp_auth";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  initUserEmailRecovery = async (
    input: SdkApiTypes.TInitUserEmailRecoveryBody
  ): Promise<SdkApiTypes.TInitUserEmailRecoveryResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/init_user_email_recovery",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY",
      },
      "initUserEmailRecoveryResult"
    );
  };

  stampInitUserEmailRecovery = async (
    input: SdkApiTypes.TInitUserEmailRecoveryBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/init_user_email_recovery";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  oauth = async (
    input: SdkApiTypes.TOauthBody
  ): Promise<SdkApiTypes.TOauthResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/oauth",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_OAUTH",
      },
      "oauthResult"
    );
  };

  stampOauth = async (
    input: SdkApiTypes.TOauthBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/oauth";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  otpAuth = async (
    input: SdkApiTypes.TOtpAuthBody
  ): Promise<SdkApiTypes.TOtpAuthResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/otp_auth",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_OTP_AUTH",
      },
      "otpAuthResult"
    );
  };

  stampOtpAuth = async (
    input: SdkApiTypes.TOtpAuthBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/otp_auth";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  recoverUser = async (
    input: SdkApiTypes.TRecoverUserBody
  ): Promise<SdkApiTypes.TRecoverUserResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/recover_user",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_RECOVER_USER",
      },
      "recoverUserResult"
    );
  };

  stampRecoverUser = async (
    input: SdkApiTypes.TRecoverUserBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/recover_user";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  rejectActivity = async (
    input: SdkApiTypes.TRejectActivityBody
  ): Promise<SdkApiTypes.TRejectActivityResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.activityDecision("/public/v1/submit/reject_activity", {
      parameters: rest,
      organizationId: organizationId ?? this.config.organizationId,
      timestampMs: timestampMs ?? String(Date.now()),
      type: "ACTIVITY_TYPE_REJECT_ACTIVITY",
    });
  };

  stampRejectActivity = async (
    input: SdkApiTypes.TRejectActivityBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/reject_activity";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  removeOrganizationFeature = async (
    input: SdkApiTypes.TRemoveOrganizationFeatureBody
  ): Promise<SdkApiTypes.TRemoveOrganizationFeatureResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/remove_organization_feature",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_REMOVE_ORGANIZATION_FEATURE",
      },
      "removeOrganizationFeatureResult"
    );
  };

  stampRemoveOrganizationFeature = async (
    input: SdkApiTypes.TRemoveOrganizationFeatureBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/remove_organization_feature";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  setOrganizationFeature = async (
    input: SdkApiTypes.TSetOrganizationFeatureBody
  ): Promise<SdkApiTypes.TSetOrganizationFeatureResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/set_organization_feature",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_SET_ORGANIZATION_FEATURE",
      },
      "setOrganizationFeatureResult"
    );
  };

  stampSetOrganizationFeature = async (
    input: SdkApiTypes.TSetOrganizationFeatureBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/set_organization_feature";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  signRawPayload = async (
    input: SdkApiTypes.TSignRawPayloadBody
  ): Promise<SdkApiTypes.TSignRawPayloadResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/sign_raw_payload",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2",
      },
      "signRawPayloadResult"
    );
  };

  stampSignRawPayload = async (
    input: SdkApiTypes.TSignRawPayloadBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/sign_raw_payload";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  signRawPayloads = async (
    input: SdkApiTypes.TSignRawPayloadsBody
  ): Promise<SdkApiTypes.TSignRawPayloadsResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/sign_raw_payloads",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_SIGN_RAW_PAYLOADS",
      },
      "signRawPayloadsResult"
    );
  };

  stampSignRawPayloads = async (
    input: SdkApiTypes.TSignRawPayloadsBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/sign_raw_payloads";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  signTransaction = async (
    input: SdkApiTypes.TSignTransactionBody
  ): Promise<SdkApiTypes.TSignTransactionResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/sign_transaction",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_SIGN_TRANSACTION_V2",
      },
      "signTransactionResult"
    );
  };

  stampSignTransaction = async (
    input: SdkApiTypes.TSignTransactionBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/sign_transaction";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  updatePolicy = async (
    input: SdkApiTypes.TUpdatePolicyBody
  ): Promise<SdkApiTypes.TUpdatePolicyResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/update_policy",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_UPDATE_POLICY",
      },
      "updatePolicyResult"
    );
  };

  stampUpdatePolicy = async (
    input: SdkApiTypes.TUpdatePolicyBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/update_policy";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  updatePrivateKeyTag = async (
    input: SdkApiTypes.TUpdatePrivateKeyTagBody
  ): Promise<SdkApiTypes.TUpdatePrivateKeyTagResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/update_private_key_tag",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_UPDATE_PRIVATE_KEY_TAG",
      },
      "updatePrivateKeyTagResult"
    );
  };

  stampUpdatePrivateKeyTag = async (
    input: SdkApiTypes.TUpdatePrivateKeyTagBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/update_private_key_tag";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  updateRootQuorum = async (
    input: SdkApiTypes.TUpdateRootQuorumBody
  ): Promise<SdkApiTypes.TUpdateRootQuorumResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/update_root_quorum",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_UPDATE_ROOT_QUORUM",
      },
      "updateRootQuorumResult"
    );
  };

  stampUpdateRootQuorum = async (
    input: SdkApiTypes.TUpdateRootQuorumBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/update_root_quorum";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  updateUser = async (
    input: SdkApiTypes.TUpdateUserBody
  ): Promise<SdkApiTypes.TUpdateUserResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/update_user",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_UPDATE_USER",
      },
      "updateUserResult"
    );
  };

  stampUpdateUser = async (
    input: SdkApiTypes.TUpdateUserBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl = this.config.apiBaseUrl + "/public/v1/submit/update_user";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };

  updateUserTag = async (
    input: SdkApiTypes.TUpdateUserTagBody
  ): Promise<SdkApiTypes.TUpdateUserTagResponse> => {
    const { organizationId, timestampMs, ...rest } = input;
    return this.command(
      "/public/v1/submit/update_user_tag",
      {
        parameters: rest,
        organizationId: organizationId ?? this.config.organizationId,
        timestampMs: timestampMs ?? String(Date.now()),
        type: "ACTIVITY_TYPE_UPDATE_USER_TAG",
      },
      "updateUserTagResult"
    );
  };

  stampUpdateUserTag = async (
    input: SdkApiTypes.TUpdateUserTagBody
  ): Promise<TSignedRequest | undefined> => {
    if (!this.config.stamper) {
      return undefined;
    }
    const fullUrl =
      this.config.apiBaseUrl + "/public/v1/submit/update_user_tag";
    const body = JSON.stringify(input);
    const stamp = await this.config.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };
}
