export const gasStationAbi = [
  {
    inputs: [
      { internalType: "address", name: "_tkGasDelegate", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ExecutionFailed", type: "error" },
  { inputs: [], name: "InvalidFunctionSelector", type: "error" },
  { inputs: [], name: "NotDelegated", type: "error" },
  { stateMutability: "nonpayable", type: "fallback" },
  {
    inputs: [],
    name: "TK_GAS_DELEGATE",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "address", name: "_erc20", type: "address" },
      { internalType: "address", name: "_spender", type: "address" },
      { internalType: "uint256", name: "_approveAmount", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "approveThenExecute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "address", name: "_erc20", type: "address" },
      { internalType: "address", name: "_spender", type: "address" },
      { internalType: "uint256", name: "_approveAmount", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "approveThenExecuteReturns",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "bytes", name: "_signature", type: "bytes" },
      { internalType: "uint128", name: "_nonce", type: "uint128" },
    ],
    name: "burnNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_target", type: "address" },
      {
        components: [
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct IBatchExecution.Call[]",
        name: "_calls",
        type: "tuple[]",
      },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "executeBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_target", type: "address" },
      {
        components: [
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct IBatchExecution.Call[]",
        name: "_calls",
        type: "tuple[]",
      },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "executeBatchReturns",
    outputs: [{ internalType: "bytes[]", name: "", type: "bytes[]" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "executeReturns",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_targetEoA", type: "address" }],
    name: "getNonce",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "uint128", name: "_nonce", type: "uint128" },
      { internalType: "uint32", name: "_deadline", type: "uint32" },
      { internalType: "address", name: "_erc20Contract", type: "address" },
      { internalType: "address", name: "_spender", type: "address" },
      { internalType: "uint256", name: "_approveAmount", type: "uint256" },
      { internalType: "address", name: "_outputContract", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "bytes", name: "_arguments", type: "bytes" },
    ],
    name: "hashApproveThenExecute",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "uint128", name: "_counter", type: "uint128" },
      { internalType: "uint32", name: "_deadline", type: "uint32" },
      { internalType: "address", name: "_sender", type: "address" },
    ],
    name: "hashArbitrarySessionExecution",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "uint128", name: "_nonce", type: "uint128" },
      { internalType: "uint32", name: "_deadline", type: "uint32" },
      {
        components: [
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct IBatchExecution.Call[]",
        name: "_calls",
        type: "tuple[]",
      },
    ],
    name: "hashBatchExecution",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "uint128", name: "_nonce", type: "uint128" },
    ],
    name: "hashBurnNonce",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "uint128", name: "_counter", type: "uint128" },
    ],
    name: "hashBurnSessionCounter",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "uint128", name: "_nonce", type: "uint128" },
      { internalType: "uint32", name: "_deadline", type: "uint32" },
      { internalType: "address", name: "_outputContract", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "bytes", name: "_arguments", type: "bytes" },
    ],
    name: "hashExecution",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "uint128", name: "_counter", type: "uint128" },
      { internalType: "uint32", name: "_deadline", type: "uint32" },
      { internalType: "address", name: "_sender", type: "address" },
      { internalType: "address", name: "_outputContract", type: "address" },
    ],
    name: "hashSessionExecution",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_targetEoA", type: "address" }],
    name: "isDelegated",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "bytes32", name: "_hash", type: "bytes32" },
      { internalType: "bytes", name: "_signature", type: "bytes" },
    ],
    name: "validateSignature",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
