export const reimbursableGasStationAbi = [
  {
    inputs: [
      { internalType: "address", name: "_priceFeed", type: "address" },
      { internalType: "address", name: "_tkGasDelegate", type: "address" },
      {
        internalType: "address",
        name: "_reimbursementAddress",
        type: "address",
      },
      { internalType: "address", name: "_reimbursementErc20", type: "address" },
      { internalType: "uint16", name: "_gasFeeBasisPoints", type: "uint16" },
      { internalType: "uint256", name: "_minimumGasFee", type: "uint256" },
      { internalType: "uint256", name: "_maxDepositLimit", type: "uint256" },
      {
        internalType: "uint256",
        name: "_minimumTransactionGasLimitWei",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "GasLimitExceeded", type: "error" },
  { inputs: [], name: "InsufficientBalance", type: "error" },
  { inputs: [], name: "InvalidPrice", type: "error" },
  { inputs: [], name: "InvalidSessionSignature", type: "error" },
  { inputs: [], name: "NotDelegated", type: "error" },
  { inputs: [], name: "TransactionGasLimitTooLow", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_ethAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_erc20",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_approveAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "ApproveThenExecuteFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_callsLength",
        type: "uint256",
      },
    ],
    name: "BatchExecutionFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_ethAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "ExecutionFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_gasChange",
        type: "uint256",
      },
    ],
    name: "GasChangeReturned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_gasUsed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_reimbursementAmount",
        type: "uint256",
      },
    ],
    name: "GasReimbursed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "GasUnpaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
    ],
    name: "InitialDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "TransferFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "TransferFailedUnclaimedStored",
    type: "event",
  },
  {
    inputs: [],
    name: "BASE_GAS_FEE_ERC20",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ERC20_TRANSFER_SUCCEEDED_RETURN_DATA_CHECK",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GAS_FEE_BASIS_POINTS",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_DEPOSIT_LIMIT_ERC20",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MINIMUM_TRANSACTION_GAS_LIMIT_WEI",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRICE_FEED_DECIMALS",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REIMBURSEMENT_ADDRESS",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REIMBURSEMENT_ERC20",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REIMBURSEMENT_ERC20_TOKEN",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REIMBURSEMENT_TOKEN_DECIMALS",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TEN_TO_18_PLUS_PRICE_FEED_DECIMALS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TEN_TO_REIMBURSEMENT_TOKEN_DECIMALS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TK_GAS_DELEGATE",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_transactionGasLimitWei",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_packedSessionSignatureData",
        type: "bytes",
      },
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "address", name: "_erc20", type: "address" },
      { internalType: "address", name: "_spender", type: "address" },
      { internalType: "uint256", name: "_approveAmount", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "approveThenExecute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_transactionGasLimitWei",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_packedSessionSignatureData",
        type: "bytes",
      },
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "address", name: "_erc20", type: "address" },
      { internalType: "address", name: "_spender", type: "address" },
      { internalType: "uint256", name: "_approveAmount", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "approveThenExecuteReturns",
    outputs: [{ internalType: "bytes", name: "result", type: "bytes" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_transactionGasLimitWei",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_packedSessionSignatureData",
        type: "bytes",
      },
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "bytes", name: "_signature", type: "bytes" },
      { internalType: "uint128", name: "_counter", type: "uint128" },
    ],
    name: "burnCounter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_transactionGasLimitWei",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_packedSessionSignatureData",
        type: "bytes",
      },
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "bytes", name: "_signature", type: "bytes" },
      { internalType: "uint128", name: "_nonce", type: "uint128" },
    ],
    name: "burnNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_targetEoA", type: "address" },
      { internalType: "uint128", name: "_counter", type: "uint128" },
    ],
    name: "checkSessionCounterExpired",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "claimUnclaimedGasReimbursements",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_transactionGasLimitWei",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_packedSessionSignatureData",
        type: "bytes",
      },
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_transactionGasLimitWei",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_packedSessionSignatureData",
        type: "bytes",
      },
      { internalType: "address", name: "_target", type: "address" },
      {
        components: [
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct IBatchExecution.Call[]",
        name: "_calls",
        type: "tuple[]",
      },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "executeBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_transactionGasLimitWei",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_packedSessionSignatureData",
        type: "bytes",
      },
      { internalType: "address", name: "_target", type: "address" },
      {
        components: [
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint256", name: "value", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct IBatchExecution.Call[]",
        name: "_calls",
        type: "tuple[]",
      },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "executeBatchReturns",
    outputs: [{ internalType: "bytes[]", name: "result", type: "bytes[]" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_initialDepositERC20",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_transactionGasLimitWei",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_packedSessionSignatureData",
        type: "bytes",
      },
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_ethAmount", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "executeReturns",
    outputs: [{ internalType: "bytes", name: "result", type: "bytes" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_targetEoA", type: "address" }],
    name: "getNonce",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_targetEoA", type: "address" }],
    name: "isDelegated",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "unclaimedGasReimbursements",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
