// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file com/daml/ledger/api/v2/interactive/interactive_submission_common_data.proto (package com.daml.ledger.api.v2.interactive, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Identifier, Value } from "../value_pb";
import { file_com_daml_ledger_api_v2_value } from "../value_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file com/daml/ledger/api/v2/interactive/interactive_submission_common_data.proto.
 */
export const file_com_daml_ledger_api_v2_interactive_interactive_submission_common_data: GenFile = /*@__PURE__*/
  fileDesc("Cktjb20vZGFtbC9sZWRnZXIvYXBpL3YyL2ludGVyYWN0aXZlL2ludGVyYWN0aXZlX3N1Ym1pc3Npb25fY29tbW9uX2RhdGEucHJvdG8SImNvbS5kYW1sLmxlZGdlci5hcGkudjIuaW50ZXJhY3RpdmUilAEKCUdsb2JhbEtleRI3Cgt0ZW1wbGF0ZV9pZBgBIAEoCzIiLmNvbS5kYW1sLmxlZGdlci5hcGkudjIuSWRlbnRpZmllchIUCgxwYWNrYWdlX25hbWUYAiABKAkSKgoDa2V5GAMgASgLMh0uY29tLmRhbWwubGVkZ2VyLmFwaS52Mi5WYWx1ZRIMCgRoYXNoGAQgASgMImsKGEdsb2JhbEtleVdpdGhNYWludGFpbmVycxI6CgNrZXkYASABKAsyLS5jb20uZGFtbC5sZWRnZXIuYXBpLnYyLmludGVyYWN0aXZlLkdsb2JhbEtleRITCgttYWludGFpbmVycxgCIAMoCUJ0CiJjb20uZGFtbC5sZWRnZXIuYXBpLnYyLmludGVyYWN0aXZlQilJbnRlcmFjdGl2ZVN1Ym1pc3Npb25Db21tb25EYXRhT3V0ZXJDbGFzc6oCIkNvbS5EYW1sLkxlZGdlci5BcGkuVjIuSW50ZXJhY3RpdmViBnByb3RvMw", [file_com_daml_ledger_api_v2_value]);

/**
 * @generated from message com.daml.ledger.api.v2.interactive.GlobalKey
 */
export type GlobalKey = Message<"com.daml.ledger.api.v2.interactive.GlobalKey"> & {
  /**
   * The identifier uses the package-id reference format.
   *
   * Required
   *
   * @generated from field: com.daml.ledger.api.v2.Identifier template_id = 1;
   */
  templateId?: Identifier | undefined;

  /**
   * Required
   *
   * @generated from field: string package_name = 2;
   */
  packageName: string;

  /**
   * Required
   *
   * @generated from field: com.daml.ledger.api.v2.Value key = 3;
   */
  key?: Value | undefined;

  /**
   * Required: must be non-empty
   *
   * @generated from field: bytes hash = 4;
   */
  hash: Uint8Array;
};

/**
 * Describes the message com.daml.ledger.api.v2.interactive.GlobalKey.
 * Use `create(GlobalKeySchema)` to create a new message.
 */
export const GlobalKeySchema: GenMessage<GlobalKey> = /*@__PURE__*/
  messageDesc(file_com_daml_ledger_api_v2_interactive_interactive_submission_common_data, 0);

/**
 * @generated from message com.daml.ledger.api.v2.interactive.GlobalKeyWithMaintainers
 */
export type GlobalKeyWithMaintainers = Message<"com.daml.ledger.api.v2.interactive.GlobalKeyWithMaintainers"> & {
  /**
   * The key
   *
   * Required
   *
   * @generated from field: com.daml.ledger.api.v2.interactive.GlobalKey key = 1;
   */
  key?: GlobalKey | undefined;

  /**
   * Key maintainers
   *
   * Required: must be non-empty
   *
   * @generated from field: repeated string maintainers = 2;
   */
  maintainers: string[];
};

/**
 * Describes the message com.daml.ledger.api.v2.interactive.GlobalKeyWithMaintainers.
 * Use `create(GlobalKeyWithMaintainersSchema)` to create a new message.
 */
export const GlobalKeyWithMaintainersSchema: GenMessage<GlobalKeyWithMaintainers> = /*@__PURE__*/
  messageDesc(file_com_daml_ledger_api_v2_interactive_interactive_submission_common_data, 1);

