name: js-build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual invocation

concurrency:
  # We only want to cancel previous builds on PRs and let the pushes to main complete
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml

  test-prod:
    name: Test (prod)
    needs: build
    uses: ./.github/workflows/reusable-test-prod.yml
    secrets: inherit

  test-pre-prod:
    name: Test (pre-prod)
    needs: build
    uses: ./.github/workflows/reusable-test-pre-prod.yml
    secrets: inherit

  test-end-to-end:
    name: Test (end-to-end)
    needs: build
    uses: ./.github/workflows/reusable-test-end-to-end.yml
