name: js-build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual invocation

concurrency:
  # We only want to cancel previous builds on PRs and let the pushes to main complete
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml

  workers:
    name: Workers (no Node compatibility)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup JS
        uses: ./.github/actions/js-setup
      - name: Build SDK server and dependencies
        run: pnpm build --filter=@turnkey/sdk-server...
      - name: Test SDK server
        run: pnpm --filter @turnkey/sdk-server test --runInBand
      - name: Test Workers import
        run: pnpm --filter @turnkey/sdk-server test:workers

  test-prod:
    name: Test (prod)
    needs: build
    uses: ./.github/workflows/reusable-test-prod.yml
    secrets: inherit

  test-pre-prod:
    name: Test (pre-prod)
    needs: build
    uses: ./.github/workflows/reusable-test-pre-prod.yml
    secrets: inherit

  # e2e tests are too flakey
  # test-end-to-end:
  #   name: Test (end-to-end)
  #   needs: build
  #   uses: ./.github/workflows/reusable-test-end-to-end.yml
