name: Publish manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (leave empty to auto-generate v{year}.{month}.{counter})"
        required: false
        type: string

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0 # required for git tags and history

      - name: Generate default version if not provided
        id: generate-version
        run: |
          # Grab the version from the input
          VERSION="${{ inputs.version }}"

          # If not provided, auto-generate
          if [ -z "$VERSION" ]; then
            VERSION=$(./.github/scripts/get-version.sh)
          fi

          # Don't forget to check
          ./.github/scripts/check-version.sh "$VERSION"
          
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  publish:
    name: Publish
    needs: version
    uses: ./.github/workflows/reusable-publish.yml
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}