name: Test

on:
  workflow_call:
    secrets:
      API_PUBLIC_KEY:
      API_PRIVATE_KEY:
      BANNED_TO_ADDRESS:
      BASE_URL:
      ORGANIZATION_ID:
      PRIVATE_KEY_ID:
      EXPECTED_PRIVATE_KEY_ETH_ADDRESS:
      EXPECTED_PRIVATE_KEY_ETH_ADDRESS_2:
      EXPECTED_WALLET_ACCOUNT_ETH_ADDRESS:
      EXPECTED_WALLET_ACCOUNT_ETH_ADDRESS_2:
      SOLANA_TEST_ORG_API_PRIVATE_KEY:
      WALLET_ID:

env:
  NODE_ENV: production

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      anvil:
        image: ghcr.io/foundry-rs/foundry:1.7.1@sha256:8347b728d5d393dac1c018691b36f506d23b9dcd78341d40ea0fcb11c3a19cdd
        entrypoint: anvil
        command: --host=0.0.0.0
        options:
          --health-cmd "cast block-number --rpc-url http://localhost:8545"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8545:8545
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Install and cache JS toolchain and dependencies (node_modules)
      - name: Setup JS
        uses: ./.github/actions/js-setup

      - name: Build
        run: pnpm build --filter='./packages/*'

      - name: Test
        run: pnpm test --concurrency=1
        env:
          NODE_ENV: development
          API_PUBLIC_KEY: ${{ secrets.API_PUBLIC_KEY }}
          API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          EXPECTED_PRIVATE_KEY_ETH_ADDRESS: ${{ secrets.EXPECTED_PRIVATE_KEY_ETH_ADDRESS }}
          EXPECTED_PRIVATE_KEY_ETH_ADDRESS_2: ${{ secrets.EXPECTED_PRIVATE_KEY_ETH_ADDRESS_2 }}
          EXPECTED_WALLET_ACCOUNT_ETH_ADDRESS: ${{ secrets.EXPECTED_WALLET_ACCOUNT_ETH_ADDRESS }}
          EXPECTED_WALLET_ACCOUNT_ETH_ADDRESS_2: ${{ secrets.EXPECTED_WALLET_ACCOUNT_ETH_ADDRESS_2 }}
          BANNED_TO_ADDRESS: ${{ secrets.BANNED_TO_ADDRESS }}
          SOLANA_TEST_ORG_API_PRIVATE_KEY: ${{ secrets.SOLANA_TEST_ORG_API_PRIVATE_KEY }}
          WALLET_ID: ${{ secrets.WALLET_ID }}
